### ISSUE TITLE
Deploy from a locally checked out repository

### ISSUE THREAD

**Issue by pkuczynski** [capistrano/capistrano#1050]
The machine I am trying to deploy to does not have access to the git repository with my application code. In Capistrano 2 this was not a problem when configured with:

``` ruby
set :repository, "."
set :deploy_via, :copy
```

Unfortunately this is not possible anymore with Capistrano 3. Any reason why and suggestion how can I solve this? 

It also does not seem to make a lot of sense to me, when I deploy to N-machine to have a need to fetch from repo and compile rails assets separately on every server, whilst I could do it only once on my build machine...

Any comments or help is greatly appreciated, as this is a show stopper from using Capistrano 3.

**Comment by trejkaz** [comment]
The copy strategy was useful for us. Not everyone is working on [I would say "toy", but the right word might be "royalty-free"] projects where they can just be stored in GitHub, and in our case, company policy states that we're not allowed to host a mirror of the repository physically outside the office. It doesn't matter that the code has to be on the server in order to execute it. The board of directors don't understand that and don't care to hear an explanation either.

So I'm currently here, wondering whether I can update to Capistrano 3, but the lack of this SCM is breaking my deployment. Of course, the way `:copy` worked wasn't perfect either, because it was copying the current contents of the directory, which may have had local modifications.

I have read the example from the blog already, but didn't find it very useful because I don't have enough practice writing custom rake tasks so it wasn't immediately obvious how to wedge that in such that it would still use the right SCM to check out the `repo_url`, but not check it out on the other side of the connection. I attempted to use `set :scm, :none` as a workaround for that but that file seemingly doesn't exist.

I also attempted to use a `:gitcopy` alternative SCM which someone heavily posted as a solution on multiple posts, forums and question sites, but of course we're using SVN, and the process of modifying the structure of that thing to suit SVN was not immediately apparent, but I think I'm getting closer to hammering it into a usable state, even if it might take a few days to figure out.

A complete example would be really helpful, if anyone who reads this has managed to get cap to work.

**Comment by mattbrictson** [comment]
> Not everyone is working on [I would say "toy", but the right word might be "royalty-free"] projects

I'm not sure if you are trolling with this comment, but I will take the bait and point out that Capistrano absolutely works with commercial projects. There is no need for a repository to be public or "royalty-free" in order to use it. I use Capistrano to deploy commercial projects every day, as I'm sure many other people do. You can use private repositories on GitHub or Bitbucket, private GitLab, etc. So to be clear: we are not intentionally ignoring the needs of commercial developers, because we (the Capistrano maintainers) have day jobs as commercial developers where we use Capistrano.

That said, the technology that makes it easy for commercial users of Capistrano is Git over SSH. In this scenario, your SSH key is forwarded to the server, which then uses it to authenticate to a private Git repository.

Since you use SVN, you might have a different perspective. I can imagine that implementing private repositories with SVN could be harder. Still, Capistrano supports SVN authentication with username and password, and SVN (as I understand it) can be deployed over HTTPS, so certainly you could securely deploy private SVN repositories in that way? Or I suppose you could use a VPN?

However, if your IT department forbids you from accessing your SVN repository from the server you are deploying to, then I guess you are out of luck in terms of Capistrano's built-in deployment strategy. And I realize that it must be doubly frustrating for you since Capistrano used to have a copy strategy.

As has been already mentioned on this thread, the Capistrano team has no plans for reintroducing a copy strategy as part of the core codebase. But the community is welcome to contribute their own plugins. We are also working on making the plugin system easier to use (see #1572), which hopefully will lead to more and better SCM plugins for you to try.

**Comment by will-in-wi** [comment]
I'll add to this that I've deployed SVN projects with Capistrano and use GitLab (not GitHub) internally extensively. 800+ employee enterprise here, we use Capistrano for deploying dozens of Rails, PHP, and Perl applications.

Once #1572 gets merged, I'll add Copy to my shortlist of SVN plugins to try to write. That one might be tricky as Capistrano assumes that the server can access the files.

There are plenty of situations where Capistrano isn't the right tool for the job, and yours might be one of them. I've used Make files with rsync for situations where I don't have a VCS Capistrano can hit.

Good luck on figuring this out!

**Comment by trejkaz** [comment]
The comment about toy projects was echoing one of the Capistrano developers here, who was calling projects "toy projects" just because they wanted the copy strategy, making wild claims like that you would only use that strategy if your code weren't in source control. The flip-side view I'm putting forward is that you would only _not_ use that strategy if your company policy is lax about where it puts its source code. Anyone in a company that controls its code strictly currently has no clean way to get the code to the server.

We're additionally unlucky enough to still be using SVN here, but I think we could probably fix that one issue if it were the only thing posing a problem. The best case scenario under the current policies at work would see us get GitHub Enterprise, so we could at least use the features of GitHub without having to put the code outside the office. Capistrano 3 still wouldn't work, though, because it's running the checkout on the wrong side of the connection in the first place.

I have been trying to attack the problem from two angles.

Option 1. Hack in a task to do the checkout and copy programmatically as a normal rake task, while putting in some kind of hack to disable SCM so that it doesn't actually try to check the code out. It seems there used to be a "none" SCM, but when I tried using that, it was still checking out the code, so I assume that's gone too. I can surely use the SCM extension mechanism to make a "none" SCM, though, so that might be the next thing to try down this path.

Option 2. Try to get Git to checkout from a socket forwarded on the SSH connection. This would allow me to use sensible project config, at the expense of some funny SSH options. But I have been digging through docs of net-ssh a lot and haven't found anything to suggest that they can do it yet. Which wouldn't be too surprising, because it's missing other modern features of SSH as well. (Case in point, the manual still says that you should use a DSA key, even though current servers don't even permit DSA keys... that issue alone already wasted a whole day of my time before I even hit the issue with SCM being run on the server!)

Maybe there's other options. Maybe there are even other tools. I guess those are all Option 3, but I haven't looked yet since I'm still trying to use what used to work.

**Comment by will-in-wi** [comment]
To make sure I understand: You are running an internal SVN server. When you say strict source control, you are referring to not allowing the code to leave your firewall.

Do you also have your application servers behind the firewall? Can your application servers access your SVN server?

The above described scenario is exactly what I have. When I initiate a deployment from my laptop (or the CI server, also behind the firewall), Capistrano connects to the application server and initiates a checkout from our VCS server (GitLab in our case, used to be SVN) and pulls it onto the application server.

I'm trying to understand your workflow since it sounds so similar to my own.

Thanks!

On an unrelated note, if you end up switching from SVN to Git and are looking for an on-prem hosted solution, I highly recommend checking out GitLab. Their omnibus packages make it very easy to use, and it is free. That made it easy for me to sell to decisionmakers where I am.

**Comment by mattbrictson** [comment]
> It seems there used to be a "none" SCM, but when I tried using that, it was still checking out the code, so I assume that's gone too.

If you want to pursue this approach, try using the branch for PR #1572. Among other things, it adds support for `set :scm, nil`.
