### ISSUE TITLE
Capfile locked at 3.1.0, but 3.2.1 is loaded

### ISSUE THREAD

**Issue by drewhamlett** [capistrano/capistrano#1056]
I've searched this and the only thing I get is to update Capistrano.  I don't want to do that because then net-ssh is all jacked.  My Gemfile.lock specifies capistrano (3.1.0) and I have

``` rb
lock '3.1.0'
```

in deploy.rb.

Am I missing something here?  Do I need to generate a bin stub or something?

**Comment by konung** [comment]
Most likely you have two versions of your gem installed as global gem. SOmething like: 
capistrano (3.8.1, 3.8.0)
By default cap command will use the latest version of the capistrano 3.8.1
And your project is locked to the one that is lower version like 3.8.0

2 simple solutions:

1. use `bundle exec cap...` - bundler will use the version that your project is locked to
2. uninstall newer (unused) version of capistrano like so `gem uninstall capistrano`

**Comment by jrochkind** [comment]
You could also have a `lock` method call in your `Capfile`, insisting on an older cap version than you are actually using in your Gemfile.  

Haven't figured out how yet how this Capfile `lock` is intended to be used, but I had to manually modify it to use a more recent cap after upgrading cap.

**Comment by mattbrictson** [comment]
I believe this is intended to be used as a safety mechanism. Many developers have several versions of Capistrano installed (e.g. the version that came with their OS, the version installed by Bundler, and perhaps several in-between), and it is easy to run `cap` instead of the more verbose `bundle exec cap`, and therefore execute the wrong version of Capistrano by mistake. Also, Capistrano is used to deploy e.g. PHP apps, and so not everyone using Capistrano is familiar with the intricacies of Bundler and rubygems versioning.

The `lock` is intended to guard against someone using the wrong Capistrano version by mistake. Unfortunately it also means that when you upgrade, you have to do it in two places: `Gemfile.lock` and also the `lock` in `deploy.rb`.

**Comment by will-in-wi** [comment]
What I do in all my apps, is to modify `lock` to be `lock '~> 3.9'`, so that it'll use anything newer than 3.9.0 but older than 4.0.

**Comment by jrochkind** [comment]
Thanks. Is this documented anywhere? Would I have had any way to know it supported operators like `~>` from docs anywhere?  Curious if there's any documentation of how it's intended to be used too.

**Comment by will-in-wi** [comment]
Good question… I came across it when I was reading the source code.

**Comment by will-in-wi** [comment]
I do not see it in the docs.

Here is a pile of examples for usage: https://github.com/capistrano/capistrano/blob/bf45cbafe5ef396933c81f334bdbc8c6d32a38c2/spec/lib/capistrano/version_validator_spec.rb

This is worth some documentation mention. I'll make a ticket.

**Comment by mattbrictson** [comment]
Would it also be nice if the `deploy.rb` generated by `cap install` used `lock "~> MAJOR.MINOR"` by default? Instead of `lock VERSION`?

**Comment by will-in-wi** [comment]
I would like that. Given that this is an old, closed ticket, perhaps continue conversation in https://github.com/capistrano/capistrano/issues/1929.

**Comment by mattbrictson** [comment]
BTW I didn't know about this feature either 😅

**Comment by mattbrictson** [comment]
Cool, I'll open a new ticket to update the `deploy.rb` template.

**Comment by mattbrictson** [comment]
#1930.

**Comment by chongfai13** [comment]
For my case

" Capfile locked at ~> 3.11.2, but 3.12.0 is loaded" 

I just changed to locked ~> 3.12.0

Problem solved.
