### ISSUE TITLE
Error "don't know how to build" when overriding cap SCM tasks

### ISSUE THREAD

**Issue by adeolaawoyemi** [capistrano/capistrano#1125]
Hi,

I'm trying to work around an svn authentication issue by overriding the `svn:update` task. My task runs fine but cap also runs the original tasks actions and according to the docs, when I use:

``` ruby
Rake::Task["svn:update"].clear_actions
```

I get the error:

``` shell
$ SVN_USERNAME=myuser SVN_PASSWORD=mypass cap qa deploy --trace
** Invoke qa (first_time)
** Execute qa
** Invoke load:defaults (first_time)
** Execute load:defaults
cap aborted!
Don't know how to build task 'svn:update'
...
```

How can I run my override task and clear_actions of predefined task without getting this error? Or is there another way to make the subversion command always use the defined username and password provided for ALL svn commands?

Thanks.

**Comment by schnittchen** [comment]
This should be re-opened. Does not work as documented.

**Comment by mattbrictson** [comment]
You're correct: clearing the default SCM tasks in particular doesn't work because the SCM tasks are not loaded and defined until *after* your deploy.rb is evaluated. Reopening.

**Comment by mattbrictson** [comment]
This is a hack, and perhaps Capistrano should provide a better way of accomplishing this, but here is one solution.

Since the SCM task you want to override is not defined until later in the boot process, you need to delay the code that does the override. My solution is to put that code inside an `after` block that hooks into `deploy:starting`.

Then you can lookup the default task, clear it, and substitute your own implementation.

```ruby
after "deploy:starting", :override_scm do
  svn_update = Rake::Task["svn:update"]
  svn_update.clear_actions
  svn_update.enhance do
    puts "Running custom svn:update instead"
  end
end
```

**Comment by leehambley** [comment]
That is unfortunate, good call @mattbrictson - I wonder if we can fix the load ordering, somehow - I would have lost hours to this.

**Comment by mattbrictson** [comment]
> I wonder if we can fix the load ordering, somehow

@leehambley I'm not sure there is a way to fix this and guarantee backwards compatibility. We can't know for certain what SCM the user has specified until we evaluate `deploy.rb`, because that file might contain e.g. `set :scm, :svn`. But then the SCM isn't loaded yet, so task enhancements fail.

One solution would be to load *all* built-in SCMs up front. I don't see any downsides to having git, hg, and svn tasks defined; only the specified SCM is actually invoked during the deploy tasks.

To maintain compatibility with custom SCMs, we still need to do the deferred loading. Furthermore, if a custom SCM has made assumptions about the default SCMs not being loaded yet, then they could break. (I think this is unlikely.)

So the new loading order would be:

1. Load all built-in SCMs
2. Load `deploy.rb`
3. Load `capistrano/#{fetch(:scm)}` if it is *not* one of the built-ins

Or we could just rewrite the SCM system to make it truly pluggable. :wink:

**Comment by leehambley** [comment]
> One solution would be to load all built-in SCMs up front. I don't see any downsides to having git, hg, and svn tasks defined; only the specified SCM is actually invoked during the deploy tasks.

I'm REALLY keen on pulling them out into their own Gems. So that we can pull in `gem 'capistrano-git'` and then require `/simple` or `/with-submodules` or something similar. Maybe we can cram all the existing behaviour into one, but the Git implementation at least is often pulled left and right by people with different needs.

**Comment by mattbrictson** [comment]
Capistrano 3.7.0.beta1 has been released! 🎉 

This version brings a new SCM plugin system, and notably for observers of this thread, this makes it much easier to override pieces of the SCM behavior. SCM is now installed via your Capfile, which means the SCM tasks are loaded and available for you to override in `deploy.rb`. You can also customize SCM behavior by subclassing to create your own plugin.

More info here:

* [Custom SCM](http://capistranorb.com/documentation/advanced-features/custom-scm/) (official how-to from the docs)
* [Capistrano 3.7.0 upgrade guide](https://github.com/capistrano/capistrano/blob/master/UPGRADING-3.7.md)

Please test the beta and send us feedback!
