### ISSUE TITLE
Linking files fails

### ISSUE THREAD

**Issue by RobinClowers** [capistrano/capistrano#1132]
It looks like it tests for the linked file but never tries to create the link. This is the output from `cap vagrant deploy --trace`

```
** Invoke deploy:check:linked_files (first_time)
** Execute deploy:check:linked_files
DEBUG[7780bb35] Running /usr/bin/env [ -f /srv/photo_album/shared/.env ] on 11.0.0.2
DEBUG[7780bb35] Command: [ -f /srv/photo_album/shared/.env ]
DEBUG[7780bb35] Finished in 0.003 seconds with exit status 1 (failed).
ERRORlinked file /srv/photo_album/shared/.env does not exist on 11.0.0.2
```

**Comment by patricknelson** [comment]
Is it possible to configure this such that it doesn't fail if the file doesn't exist (i.e. Optional linked files)? e.g. My app may not require the file, but if the file does exist, it will use it and should still be retained between releases.

**Comment by mattbrictson** [comment]
@patricknelson no, there is not such a feature. Could you help me understand your use-case a bit more? Why are the files optional?

**Comment by patricknelson** [comment]
In this case, it's because I deploy to about 6 environments which vary depending on their use case (Prod + DR, UAT, QA, Dev and agency). In most situations the private key file I'm symlinking will exist, but it's only optionally needed depending on other configuration (in this case: SSO). If SSO is disabled, you can login normally via user/pass (which you can do even with SSO enabled in the off chance SSO is failing). 

In this way, I have the ability to be more robust and deploy to environments during my transition period as we dev/debug SSO. It's not a huge deal since it's easy to set up, I was simply researching if it was possible since I'd like to not have to create an empty file for an environment which may not ever be setup with SSO.

**Comment by mattbrictson** [comment]
I see.  Thanks for the explanation! We don't have plans to support optional linked files in Capistrano itself any time soon, but it sounds like you have some viable workarounds.

**Comment by speckins** [comment]
@patricknelson I came across this issue while Googling for the same thing.  I ended up making a custom task using the [deploy:symlink:linked_files](https://github.com/capistrano/capistrano/blob/7a1b7c05ef0503010462a60a84c6957b5cd99ecd/lib/capistrano/tasks/deploy.rake#L131) task as a starting point and just added a line to skip creating a symlink unless the file exists.

```ruby
# lib/capistrano/tasks/optional_linked_files.rake
namespace :deploy do
  namespace :symlink do

    task :shared do
      invoke "deploy:symlink:optional_linked_files"
    end

    desc 'Symlink optional linked files'
    task :optional_linked_files do
      next unless any? :optional_linked_files
      on release_roles :all do
        execute :mkdir, "-p", linked_file_dirs(release_path)

        fetch(:optional_linked_files).each do |file|
          target = release_path.join(file)
          source = shared_path.join(file)
          next unless test "[ -f #{source} ]"
          next if test "[ -L #{target} ]"
          execute :rm, target if test "[ -f #{target} ]"
          execute :ln, "-s", source, target
        end
      end
    end

  end
end

# config/deploy.rb or config/deploy/<stage_name>.rb
set :optional_linked_files, %w{
  .env
}
```

**Comment by patricknelson** [comment]
Brilliant, thanks @speckins for the quick snippet! I wasn't sure how much demand there'd be for this so I figured someone had to ask first.

n00b question: Is there any way to incorporate this locally into my project repo (e.g. somewhere adjacent to `deploy.rb`) instead of dropping into my `capistrano` install directory (i.e. all the way under `/usr/local/share/gems/gems/capistrano-VERSION/lib/capistrano/tasks/` on my CentOS local dev server)?

**Comment by speckins** [comment]
@patricknelson Yes, there is a place for you to add custom Capistrano tasks to your project, usually {Rails.root}/lib/capistrano/tasks/ -- look at the end of your Capfile.  Take the entirety of the code I posted above (minus the `set :optional_linked_files, ...` part that goes in config/deploy.rb) and put it in a file under that directory (such as lib/capistrano/tasks/optional_linked_files.rake).

**Comment by patricknelson** [comment]
@speckins Thanks for the tip! I tested this and of course it works beautifully. Thanks for making it easy plug-n-play 👍
