### ISSUE TITLE
Compatibility with Ruby 1.9.2

### ISSUE THREAD

**Issue by graywh** [capistrano/capistrano#1178]
I noticed that 5333e50 uses `io/console`, which was added in Ruby 1.9.3, instead of http://github.com/JEG2/highline.  Is this intentional?

**Comment by Kriechi** [comment]
@leehambley this can be closed I suppose?

**Comment by leehambley** [comment]
I wanted to keep it open, since dropping 1.9.2 support seemed needlessly arbitrary, but with the recent noise about RubySpec, and how fundamentally broken early 1.9 releases were, and that 1.9.2 is now [already a year past EOL](https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/). I just have to double check that our README and travis.yml are up to date with the targets we support.
