### ISSUE TITLE
LoadError: cannot load such file -- capistrano/copy.rb

### ISSUE THREAD

**Issue by shenoudab** [capistrano/capistrano#1203]
Dears, 

 I'm using capistrano-scm-copy gem to support :copy of SCM Option.

Today after i update my Capistrano Version to 3.3.3 and Ruby to 2.1.5
and trying to deploy my project i got the below error:

LoadError: cannot load such file -- capistrano/copy.rb

Please, any help regarding this issue ?

**Comment by sagikazarmark** [comment]
I am aware of how old this issue is, but I am writting answer here regardless as I sent an hour with it:

After upgrading ruby, you might have to reinstall dependencies with bundler. Using `:copy` as SCM tries to manually load `capistrano/copy.rb` which might not be available after an upgrade. (It turned out it has nothing to do with the mentioned gem)

PS: @leehambley I admire how helpful your comments are. It's clear that you don't even want to help people with issues like this. (Yes, plural, not the first issue I see this)

**Comment by leehambley** [comment]
@sagikazarmark I'll thank you to keep personal attacks out of Github issues. Ruby's ecosystem is complex and varied, we have tests that test that this is not a Capistrano problem.
