### ISSUE TITLE
Metrics should be optional with an argument and stored in $HOME

### ISSUE THREAD

**Issue by luishdez** [capistrano/capistrano#1328]
Metrics default settings should be stored in the user $HOME similar as git etc. 

And to avoid CI integrations problems it should exists a --non-interactive or similar option for de cli. 
I don't think that forcing people to store files in their projects is the best solution for this settings.

Thanks!

**Comment by sponomarev** [comment]
Nice idea!

**Comment by leehambley** [comment]
We can't use $HOME because people have many Capistrano projects, and concurrent (cross platform) file access is a harder problem to solve than it ought to be. 

Regardless, closing because the metrics will go away soon enough, use an old(er) version of Capistrano if you can't work around this.

To address this point:

> And to avoid CI integrations problems it should exists a --non-interactive or similar option for de cli. 

Your CI is lying to Capistrano if you are still being prompted about it's `stdin` being a `tty`, this problem is endemic of bad CI systems (yeah, essentially all of them), and poor understandings of the what POSIX was supposed to be.
