### ISSUE TITLE
Problem while deploying

### ISSUE THREAD

**Issue by homebase-dev** [capistrano/capistrano#1330]
Hi there,

I have a problem while deploying, it seems that all operations containing the **cp -p ....** fail. E.g. 
```
*** [err :: www.test.com] cp -p public/assets/ckeditor/application-7b124a48b7a8fc90e7229bc09534aefb.css.gz public/assets/ckeditor/application.css.gz
```
Can you imagine what is wrong resp. how I can fix this? I'm really stuck with this one.

**Comment by kirs** [comment]
Firstly, your issue is related to `capistrano-rails` precompile task.
Secondly, this is not an error. `rake assets:precompile` task from Rails is using `stderr` for output.

---

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information (your versions (Ruby, Cap, etc), your Capfile, your logs, and relevant sections out of your Gemfile)

Otherwise support is done via the mailing list (https://groups.google.com/forum/#!forum/capistrano) or at StackOverflow (http://stackoverflow.com/questions/tagged/capistrano) with questions tagged capistrano.

**Comment by homebase-dev** [comment]
I will look for in the links you are advising.
Thank you very much for your help!
