### ISSUE TITLE
How to get current stage name in task?

### ISSUE THREAD

**Issue by adisos** [capistrano/capistrano#1365]
How to get current stage name in task?

**Comment by leehambley** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information (your versions (Ruby, Cap, etc), your Capfile, your logs, and relevant sections out of your Gemfile)

Otherwise support is done via the mailing list (https://groups.google.com/forum/#!forum/capistrano) or at StackOverflow (http://stackoverflow.com/questions/tagged/capistrano) with questions tagged `capistrano`.

**Comment by leehambley** [comment]
For what it's worth, it's very very simple...

``` ruby
fetch(:stage)
```

**Comment by leehambley** [comment]
Here's a trivial example:

![screenshot 2015-02-11 15 17 46](https://cloud.githubusercontent.com/assets/18952/6148373/2b2815bc-b201-11e4-8133-c18c88927296.png)

**Comment by adisos** [comment]
Thank you very much. I know how to fetch variable. But I googled before posting this issue how to find variable name, but to no avail. Later I began to look source code, reached optionparser line and stuck there. And you posted answer.

**Comment by leehambley** [comment]
I try to discourage posting "help requests" on the Github (*Issues*) tool since we have two other support forums which we maintain (IRC and the Google Group), and the community maintains stack-overflow itself.

**Comment by adisos** [comment]
Ok, my bad. I have to used post such requests with other repos. So I didn't knew it's not be encouraged.
