### ISSUE TITLE
SSH gateway support for Capistrano v 3.3.5 

### ISSUE THREAD

**Issue by ArunSakthivel** [capistrano/capistrano#1367]
` set :gateway, server_address `

This command not working in the latest version. Any idea, How to access the gateway server and I need to deploy in the production server.

In my requirement is:
To accessing the gateway server using password(RSA token) and to access the production server using ssh key. Kindly help to me, how can i get done this scenario

**Comment by leehambley** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information (your versions (Ruby, Cap, etc), your Capfile, your logs, and relevant sections out of your Gemfile)

Otherwise support is done via the mailing list (https://groups.google.com/forum/#!forum/capistrano) or at StackOverflow (http://stackoverflow.com/questions/tagged/capistrano) with questions tagged `capistrano`.

Unless you saw this documented on capistranorb.com somwhere, in which case this is a doc bug. Gateway support is under discussion at https://github.com/capistrano/capistrano/issues/725
