### ISSUE TITLE
Issue with execute nohup

### ISSUE THREAD

**Issue by yoyos** [capistrano/capistrano#1385]
Hello

I'm using 3.3.5 and I have a problem with a capistrano task I'm trying to write.

I would like to start rpush during deploy.
This task is working but is blocking my cap deploy :

```
  task :start_rpush do
    on roles(:app), in: :sequence, wait: 5 do
      execute("cd #{release_path}; rpush start -e production -f")
    end
  end
```

So I tried to use nohup but no process started on the server, don't know why :
No error, deployment ok,  but no process executed.

```
  task :start_rpush do
    on roles(:app), in: :sequence, wait: 5 do
      execute("cd #{release_path}; nohup rpush start -e production -f &> /dev/null &")
    end
  end
```

```
INFO [ba6c069c] Running /usr/bin/env cd /home/xxx/backend/releases/20150228215439; nohup rpush start -e production -f &> /dev/null & as xxx@xxx
INFO [40f8c246] Finished in 0.105 seconds with exit status 0 (successful).
```
Any Idea what's happening ?
I'm on this since this morning :/

Thanks !

**Comment by leehambley** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information (your versions (Ruby, Cap, etc), your Capfile, your logs, and relevant sections out of your Gemfile)

Otherwise support is done via the mailing list (https://groups.google.com/forum/#!forum/capistrano) or at StackOverflow (http://stackoverflow.com/questions/tagged/capistrano) with questions tagged `capistrano`.

**Comment by yoyos** [comment]
Found a way through

I added a "sleep 2" just after the nohup, and it seems it let the nohup process do its job
