### ISSUE TITLE
Do you want to enable statistics prompt breaks automated deployments

### ISSUE THREAD

**Issue by jspooner** [capistrano/capistrano#1393]
Automated deployments hang indefinitely because cap is asking the user to respond to "Do you want to enable statistics?"  To fix this you have to add .capistrano/metrics to your git project.  This is slightly ridiculous.  

https://gist.github.com/mbj/3007d6c1b9c0bc13c6fc

**Comment by carlisia** [comment]
:+1:

**Comment by gblackburn** [comment]
Yes, please fix!

**Comment by leehambley** [comment]
It is demonstrably not broken. The issue if one were due at all would be in
the capistrano/metrics repository, and it is your CI that is broken. If any
of you would care to read the changelog before spamming GH with ill
conceived issues, you would see that the most recent, and already two week
old release of Capistrano has removed the dependency on the metrics gem.

Capistrano/metrics always respected $stdin.tty? Which is the time honoured
POSIX ordained way to know it you are connected to something that can be
assumed to be interactive. The terminology "Teletype" is ancient and
virtually obsolete, in modern parlance this is usually a ptty, or pty.

If your CI is claiming to offer a TTY, as is often the case, because some
"colours" enabling  plugin or similar is installed, or because the CI is
broken by design, this will incorrectly report to well written programs
that they may reasonably expect a user to be able to respond to the prompt.

This same behaviour is transparent, and prevalent across Unix tools,
imagine how `ls` and `grep` behave differently when triggered by hand vs
when they are part of a pipeline or their output redirected to a file...
The difference is that people don't often use such tools in their CI or
really pay much attention to how they work.

Please excuse my frustration, but education, and poorly written CIs are
should not be our problem, we already sacrificed valuable metrics because
of poor design on the part of CI and other tool authors, and I'm not only
in dealing with having already fixed this, and answered many times on many
duplicate issues that this is the case, but having REMOVED this metrics
plugin weeks ago, I am *still* dealing with it.

You each, as open source patrons have a duty of diligence to use the search
functions provided by Github, and Google, StackOverflow, etc, and to try to
understand where the problem lay, to check that you are operating on valid
assumptions and current information, and given that, to make a useful and
constructive bug report to the best of your ability. If you can't
participate with the submission of a patch/fix (you'd note, there's nothing
to fix) at least you'll could instead contribute something constructive to
the discussion.

**Comment by arthurtalkgoal** [comment]
the ***"Do you want to enable statistics?*** paused my automaticed update script.  

I have .capistrano/metrics with a text ***full*** (not sure when cap created it. How can I disable the stats?

**Comment by leehambley** [comment]
You go read the CHANGELOG, and more than likely upgrade Capistrano. Also please make sure to report this to your CI provider because **their implementation of a script runnier is broken**. Report your CI info here, and I will gladly report the issue on your behalf.

**Comment by czerasz** [comment]
What helped me is the update of Capistrano to version `3.4`. Many thanks to @mvz for posting [this comment](https://github.com/capistrano/stats/issues/30#issuecomment-78234780).
