### ISSUE TITLE
can't fetch :deploy_user

### ISSUE THREAD

**Issue by turboMaCk** [capistrano/capistrano#1399]
fetch(:deploy_user) do not return deploy user name in capistrano **3.4.0**.

    # in deploy.rb
    server 'xx.xx.xx.xx', user: 'deploy', roles: %w{web app db}
    set :deploy_to, "/home/#{fetch(:deploy_user)}/apps/app"

    # console output
    DEBUG [54b4a353] 	mkdir:
    DEBUG [54b4a353] 	cannot create directory ‘/home//apps/app’
    DEBUG [54b4a353] 	: Permission denied

**Comment by leehambley** [comment]
There must be some bad documentation still floating around, where did you see this mentioned as still being valid? I'll fix that.

What you are looking for is:

``` ruby
user = "deploy"
server 'xx.xx.xx.xx', user: user, roles: %w{web app db}
set :deploy_to, "/home/#{user}/apps/app"
```

No need to use `fetch()`. Also, later if you need the username in an `on()` block it is accessible via:

``` ruby
on roles(:all) do |host|
  puts capture(:ls, "/home/#{host.user}")
  puts capture(:ls, "/home/#{user}") # same as above, uses a regular Ruby var.
end
```

**Comment by turboMaCk** [comment]
So there is not possibility to fetch some var from configuration in :deploy_to?? I'll also need to use custom property in my deploy to like:

```ruby
server 'xx.xx.xx.xx', user: 'deploy', roles: %w{web app db}, instance_name: :instance
server 'xx.xx.xx.xx', user: 'deploy', roles: %w{web app db}, instance_name: :instance2
set :deploy_to, "/home/#{fetch(:deploy_user)}/apps/#{fetch(:instance_name)}"
```

Or is there other solution for deploy to multiple directories?

**Comment by leehambley** [comment]
Not possible, sorry. `fetch()` (as is documented widely) reads values set by `set()`, the only reason to use `set()` and `fetch()` over regular ruby variables is to provide a consistent API between plugins and extensions, and because `set()` can take a `Proc` to be resolved later.

The variables you are setting in the `host` object via the `server()` command belong to an individual host, some of them, `user`, `roles`, etc have special meanings. For more information see https://github.com/capistrano/sshkit/blob/master/EXAMPLES.md#do-something-different-on-one-host-or-another-depending-on-a-host-property.

If you specifically need to deploy to a different directory on each machine you probably should not be using the built-in tasks (they don't fit your needs), and rather copy the `deploy.rake` from the Gem into your own project, and modify it as you need. Which in this case might be to not take `fetch(:deploy_to)`, but to read that from a host property.

You could *try* to do something where before doing anything that relies on calling `fetch(:deploy_to)`, you `set()` it using the value from `host.someproperty` but I'm pretty sure that'll break in exciting and interesting ways.

Can you please let me know where you found the bad docs, I'm trying really hard to make sure I correct as much misinformation on the internet about Cap stuff as I can.

**Comment by turboMaCk** [comment]
I did not find this in official documentation but in this upgrade guide (blog post): http://www.talkingquickly.co.uk/2014/01/deploying-rails-apps-to-a-vps-with-capistrano-v3/ And after looking more deeply in code => there is set method use for setting deploy_user var in script so this work almost same way as your example but with setter and getter (fetch).

**This is definetely issue with neither capistrano or documentation**

This issue should be closed. I'll try to find some other solution for this case.

**Comment by leehambley** [comment]
Alright, so I'll close the issue. As I said, if the ootb defaults don't work for you the intended *escalation* if you like is to just copy `deploy.rake` into your own project, tweak it and load it from there.
