### ISSUE TITLE
within block not executing inside the specified directory

### ISSUE THREAD

**Issue by rchady** [capistrano/capistrano#1439]
Maybe I am doing something wrong, in fact quite probably so, but when I do something simple like:

on fetch(:remote_server) do 
  within "/etc" do
    execute "echo $PWD"
  end
end

I get output of /home/deploy rather than /etc that I would expect.  The documentation says that commands in the "within" block are executed inside that directory, so why is this failing?

**Comment by leehambley** [comment]
It's an SSHKit question. Closing the issue here. As is documented if your argument to `execute()` contains whitespace it cannot safely be modified by our command parser, so we can't wrap it in the "cd" that you requested with `within('/etc/')`. We also don't warn because there's an equal chance this is exactly what you intended to do. Use `execute(:echo, "$PWD")`
