### ISSUE TITLE
Migrations not running on all db servers

### ISSUE THREAD

**Issue by jarijokinen** [capistrano/capistrano#1449]
Capistrano 3.4.0 runs migrations only on the first server that has a db role:

    server 'A', user: 'jari', roles: %w{app db web}
    server 'B', user: 'jari', roles: %w{app db web}

Result: Migrations are running only on server A.

    server 'A', user: 'jari', roles: %w{app web}
    server 'B', user: 'jari', roles: %w{app db web}

Result: Migrations are running only on server B.

Is this intended behavior?

**Comment by leehambley** [comment]
Yes, correct - there's really no need to name your "db" server in there if it's not the one you want to run migrations on. The naming is a legacy of Rails original Capistrano integration where the expectation was that your "db" server (and, of course there'd only be one) would run the migrations, and have ruby/etc installed. That role might better be called "migration runner", but we once experimented with that name, and it caused more confusion.

**Comment by jarijokinen** [comment]
I have two production servers (A and B) running the same app, but they are not related to each other and don't share any data. Both servers have own, independent database. I'd like to run migrations on both servers when calling "cap production deploy".

Capistrano runs migrations only on the first server when tagging both servers with the "db" role.

But I guess this is how it should work then, and I should impelement my deploy system in other way.

**Comment by leehambley** [comment]
You can easily just ass a task (look in the rails/migration code) to run
the same thing, for a different dB/app/whatever.

**Comment by micred** [comment]
same problem as @jarijokinen . I thinks it should not limit the migration to the first server with role DB. It has no sense.

**Comment by leehambley** [comment]
Take it up with the Rails team. The meaning of a Rails migration is to nominate one machine to make the changes to the database, why let two machines race to run `ALTER TABLE……` in separate transactions, only to have one of them fail because other writer won?

**Comment by leehambley** [comment]
> I have two production servers (A and B) running the same app, but they are not related to each other and don't share any data. Both servers have own, independent database. I'd like to run migrations on both servers when calling "cap production deploy".

This is a correct use for "stages" you need to change your configuration to support that @jarijokinen

**Comment by micred** [comment]
@leehambley, sure in fact I can nominate just one machine to do migrations assigning role :db only to that one.
Why should Capistrano limit the user to this behaviour?

I have multistage enabled (production and staging) and for both of them I have multiple hosts defined in each one.
If I run `HOSTS=first_host.domain.com cap production deploy:migrate` it runs migrations.
Otherwise if I do `HOSTS=second_host.domain.com cap production deploy:migrate` it totally ignore the migration without giving any alerts.

Yeah, it would work if I split hosts in separate stages, like first_host_production, first_host_staging, but I were not aware of the limitation when I set it up and it's not a clean solution, too, since if I want to change a parameter of the production stage (eg. webserver threads) I have to change N files.

**Comment by leehambley** [comment]
I don't understand what you expect to achieve, you cannot have more than one host making changes to your database at a given time, thus as Rails defined, and recommended (when Capistrano was a part of Rails) the built-in DB role mirrors that behaviour. If you need other behaviour, add another role, and write your own task.

**Comment by micred** [comment]
It's simple what I expect: I suggest (and can work on a PR) a better handling of multiple hosts with role :db or more documentation about this behavior.
If the user specifies the role :db on multiple hosts, it expects that migrations runs on all of them, no?!
Otherwise he would have just put the role :db on the first host.

Even more if the user is running the command on a single host like doing:
`HOSTS=second_host.domain.com cap production deploy:migrate`

**Comment by leehambley** [comment]
> It's simple what I expect: I suggest (and can work on a PR) a better handling of multiple hosts with role :db or more documentation about this behavior.

Please see capistrano/rails which deals with Rails integration, and the team there will be glad to help you (but the behaviour is correct.)

> If the user specifies the role :db on multiple hosts, it expects that migrations runs on all of them, no?!
Otherwise he would have just put the role :db on the first host.

No, migrations make changes to a shared data source, it is unsafe and incorrect (and all but the first will fail, anyway) to have multiple application servers try and make the same changes to the same database.

> Even more if the user is running the command on a single host like doing:

It is the responsibility of the `deploy/migrate` task (See capistrano/rails) to issue a warning in that case, that no hosts match.

**Comment by mattbrictson** [comment]
FYI, capistrano-rails (in master) can now run migrations on multiple hosts if you need to, although the default behavior (run on primary :db server only) is unchanged. See https://github.com/capistrano/rails/issues/168

**Comment by micred** [comment]
Thank you @mattbrictson, excellent.

**Comment by gregblass** [comment]
Glad to see there is a way to do this now. One example (my use case) is if you've got a multi-tenant server - but then you may have clients that want their own server spun off. I wrote my tenancy code to support that. Thus, I want my migrations running on all servers - not just one.
