### ISSUE TITLE
build local, deploy afterwards

### ISSUE THREAD

**Issue by dfreudenberger** [capistrano/capistrano#1488]
Hi,

do you have any plans to implement a feature to prepare the the build locally and deploy the final build to the servers? Basically what already existed with build_script and copy_strategy for version 2.x. 

Having all kind of deployment relevant software installed on every server and building the same .jar file on a dozen of servers doesn't feel right.

Best regards,
Daniel

**Comment by leehambley** [comment]
No plans, but largely because it's not necessary anymore, for two reasons:

1. We *do* have plans to make loading the SCM integration optional, when that's done, you can skip loading the Git deploy recipe, for example
2. Largely, since SSHKit was extracted, it's trivial to do something such as the following: http://lee.hambley.name/2013/06/11/using-capistrano-v3-with-chef.html

This refers to using Chef, but essentially anything where you build something locally, upload it to a server, and do something with it would work similarly.

**Comment by shaneog** [comment]
@dfreudenberger Take a look at https://github.com/wercker/capistrano-scm-copy. It might be what you're looking for.

**Comment by webflo** [comment]
https://github.com/Bladrak/capistrano-rsync works well for me.

**Comment by mattbrictson** [comment]
As @leehambley mentioned, we don't have plans to implement a build-push system, but we are working to make the SCM implementation more pluggable (and completely optional).

There are also gems available that seem to address your scenario (see previous comments).

I'll close this issue since it is not something Capistrano itself will be addressing directly.
