### ISSUE TITLE
/repo folder pointing to wrong branch

### ISSUE THREAD

**Issue by NekoNova** [capistrano/capistrano#1506]
Hello,

I'm not sure if this is a bug, or something off in our configuration, but let sketch the problem:

We're using Capistrano 3 to deploy our application. We ask for which branch to be deployed, but default to develop. Using automated deploy, we deploy branch "release-xx" to our test server after each successful build.

In our code, we use the `git` gem to read out the git information from the `/repo` folder that is created by Capistrano. But this tells us that the branch there is `develop` and not for example our `release-2.x` branch.

we originally had this in our `deploy.eb` file:

```
# Source Control Configuration
set :scm, :git
ask :branch, "develop"
```

and I changed this now into:

```
# Source Control Configuration
set :scm, :git
set(:branch, ask("Enter the name of the branch: [develop]", "develop"))
puts("setting branch to: #{fetch(:branch)}")
```

But I'm not sure if this is the correct way to do so?
Or will it even solve the problem I am having?
What I expect/want is that the `/repo` after the deploy points to the same branch  as was used in the configuration when deploying.

**Comment by leehambley** [comment]
It doesn't matter what the `/repo` folder is checked out to, what matters is the command that is used to "archive" that to the current deployment, which is where the `:branch` variable you have used is set.

Examine your Capistrano logs for "git archive" (or `git-archive`, etc) and watch how your `/repo` (the cache folder) is "archived" into the current deployment directory at a specific branch.

**Comment by NekoNova** [comment]
which means, reading out the git information will always return the same, because the `/repo` is used differently as I think?

**Comment by leehambley** [comment]
Yes, indeed (by the way, glad you can still comment on the closed issue).

The `/repo` is just a cache, it's a complete copy of your repo (well, barring unanswered questions about garbage collection/etc.) - it is used to be "updated" first, and then because it's a complete copy we use the `git archive` command to make a tarball which we streamingly unpack (sounds weird I know, there's a good reason) into the release directory.

Without the `/repo` (it used to be called `/cached-repo`, it was changed in v3, and the `develop` branch also used to be called `cache` ,but it was changed for a reason that I can't remember) we'd have to clone the whole repo every time, which can be very slow, and bandwidth expensive. With the `/repo`, we only have to refresh the local repo by doing a `git pull`, which is the only reason it's there.

From any repo you can clone any other, e.g you could do this:

    $ git clone -b anybranch git@github.com:capsistrano/capistrano    # clone from GH
    $ git clone -b anyotherbranch capistrano/                                       # clone from a local folder on another branch
    # (we could also use git-archive in place of the 2nd line)

In this example `/repo` is the first line, and on your example the value you enter at the prompt is used in place of `anyotherbranch` for checking out the specific branch the second time around.

* https://git-scm.com/docs/git-archive

**Comment by NekoNova** [comment]
okay thanks for the feedback.
