### ISSUE TITLE
Missing .git folder in release.

### ISSUE THREAD

**Issue by phlegx** [capistrano/capistrano#1540]
Hi!

I have upgraded to Capistrano 3 and now the ```.git``` folder is missing in the release folder. How can I config Capistrano to get back the ```.git``` folder on the release folder? I need this folder.

Thx

**Comment by mattbrictson** [comment]
Capistrano 3 does not work this way. It makes a copy of the git checkout to the release folder, and this copy does not include the `.git` contents. There isn't an easy way to change this, to my knowledge. I suggest searching or posting to Stack Overflow, since others may have encountered the same limitation.

--

GitHub issues is for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you try your luck at [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano). For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).

**Comment by mattbrictson** [comment]
This is a duplicate of #1222.
