### ISSUE TITLE
Cannot deploy using ruby-2.2.4

### ISSUE THREAD

**Issue by ben-clarke** [capistrano/capistrano#1544]
I have just installed ruby-2.2.4 using rbenv, after doing this I updated my server as well to 2.2.4.

I also changed the my deploy.rb file and also my gemfile to suit the recent update.

I next after a few code changes to the project committed the changes to my repo and deployed.

The deploy failed and I'm not sure why, when I deploy I get this error

```/Users/benclarke/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/capistrano-3.1.0/lib/capistrano/i18n.rb:4: warning: duplicated key at line 6 ignored: :starting
cap aborted!
Capfile locked at 3.4.0, but 3.1.0 is loaded
config/deploy.rb:2:in `<top (required)>'
/Users/benclarke/.rbenv/versions/2.2.4/bin/cap:23:in `load'
/Users/benclarke/.rbenv/versions/2.2.4/bin/cap:23:in `<main>'
Tasks: TOP => production
(See full trace by running task with --trace)```

Any suggestions to a fix or an actual fix would be appreciated.

**Comment by mattbrictson** [comment]
Hi @ben-clarke, this is a general Ruby usage question and not something Capistrano specific.

When you install a new Ruby version with rbenv, you start over with a blank slate in terms of gems. You'll need to reinstall all of the gems you need in the new Ruby.

In this case, the error message is pretty clearly saying that you need Capistrano 3.4.0. To install it, run:

```
gem install capistrano -v 3.4.0
```

Or you could put capistrano in your repo's Gemfile and use `bundle exec cap` to run it. That way you are guaranteed to always be using the right version.

Hope that helps!

--

GitHub issues is for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).
