### ISSUE TITLE
Capistrano deployment failed

### ISSUE THREAD

**Issue by BeeZerk** [capistrano/capistrano#1581]
hey, i cant deploy anymore and it drives me crazy not knowing why..

    cap aborted!
    Errno::ENOENT: No such file or directory @ rb_file_s_stat - /tmp/project.tar.gz
    Tasks: TOP => gitcopy:create_release
    (See full trace by running task with --trace)

Maybe somebody can help me. I think its an issue with capistrano, maybe some false configuration

**Comment by mattbrictson** [comment]
Hi, I see that your problem has to do with the `gitcopy:create_release` task. I'm guessing that's from this project: https://github.com/xuwupeng2000/capsitrano-scm-gitcopy. You should ask your question there.

If it turns out to be a bug in Capistrano itself, please let us know.


--

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).
