### ISSUE TITLE
Illegal option R with setfacl on FreeBSD

### ISSUE THREAD

**Issue by webdevilopers** [capistrano/capistrano#1582]
FreeBSD caused me a lot of issues. First of all I had to enable `bash` by default:
https://github.com/capistrano/symfony/issues/24

Using `acl` as `permission_method` currently fails:
```
Command: ( SYMFONY_ENV=prod /usr/bin/env setfacl -Rm u:foobar:rwx,u:foobar:rwx /usr/local/www/apache24/noexec/foobar/shared/app/logs /usr/local/www/apache24/noexec/foobar/releases/20160212200050/app/cache )
DEBUG [bc158cd7] 	setfacl: illegal option -- R
DEBUG [bc158cd7] 	usage: setfacl [-bdhkn] [-a position entries] [-m entries] [-M file] [-x entries] [-X file] [file ...]
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as foobar@example.com: Exception while executing as foobar@example.com: setfacl exit status: 1
setfacl stdout: Nothing written
setfacl stderr: setfacl: illegal option -- R
usage: setfacl [-bdhkn] [-a position entries] [-m entries] [-M file] [-x entries] [-X file] [file ...]
```

Any solution to this instead of writing a custom wrapper inside `/usr/local/bin/` grepping and replacing the `-R`?

Related:
- https://github.com/capistrano/symfony/issues/52

**Comment by mattbrictson** [comment]
Hi, I don't think there is anything we can do here in the core Capistrano project to address this. You are apparently using the capistrano-file-permissions gem, which is responsible for the `setfacl -R` command. Your best bet is to fix/change that command in that gem, and I see you've already opened an issue there: https://github.com/capistrano/file-permissions/issues/8.

If I were in your shoes, I would just fork the capistrano-file-permissions gem, remove the `-R`, and then use that fork in my project.

In your Gemfile, you can point to a fork like this:

```ruby
gem "capistrano-file-permissions", :github => "myusername/file-permissions"
```

Where the `:github` value is the username/repo of your fork. You can also specify a `:branch` if it is something other than master. [Documentation here.](http://bundler.io/git.html)

Good luck!

--

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).
