### ISSUE TITLE
New dependencies in 3.5

### ISSUE THREAD

**Issue by arteezy** [capistrano/capistrano#1655]
Today I was updating my project's gems and I've noticed something new: `airbrussh` and `capistrano-harrow`. Turns out that the latest version of Capistrano gem (3.5.0) [added 2 new dependencies](https://rubygems.org/gems/capistrano/versions/3.5.0).  First of all, adding new dependencies is considered a kinda bad thing to do, especially in such wide used project as Capistrano. We should make effort to shrink them, not blow them up. 

![harrow](https://cloud.githubusercontent.com/assets/192247/14913723/e2bbd6a0-0e26-11e6-9374-f68d01f8bac2.png)

So I thought, maybe these gems were absolutely required to make new version of Capistrano more awesome? What are they doing?
- [airbrussh](https://github.com/mattbrictson/airbrussh) - adds a new way to format Capistrano output. OK, that's a little bit useful, but totally not worth a whole extra dependency. Should be an external plugin or just a part of basic Capistrano gem.
- [capistrano-harrow](https://github.com/harrowio/capistrano-harrow) - integrates Capistrano with [Harrow.io](https://harrow.io) CI web-service. What? So, if I don't use Harrow, this gem does nothing for me? And this dud is installed on _**every machine**_ along with Capistrano gem? 

Harrow doesn't even have a free plan. Everyone is being pushed to use this service and pay money.

Worst thing is to disable this gem I have to make actions. I have to spent my time and clog my git config. Unbelievable!

I understand that maintainers of Capistrano are allowed to do anything with their own project. I also understand that their work is often unrewarded and non paid. They've probably created Harrow to support and fund further development of Capistrano. But the way this situation is handled is morally wrong and goes against open source principles. 

Imagine if Yehuda Katz added his commercial web-service [Skylight.io](https://www.skylight.io) as a dependency for `bundler` gem, which he also created? Or if DHH added Basecamp as a dependency for Rails? Just, you know, for _easier integration_ in case you'll need it sometime?

**Comment by leehambley** [comment]
> First of all, adding new dependencies is considered a kinda bad thing to do, especially in such wide used project as Capistrano.

Unnecessary dependencies maybe, but Airbrussh is a complex project in it's own right with an existing user base, and bundling it into Capistrano and forcing the maintainer to maintain two versions would be unreasonable. The recent trend about trying to strip the number of gem dependencies is a valiant one, but don't make the mistake of assuming *all* dependencies are bad, it's about sizing and making it *worth it*. Airbrussh is a separate gem for the reasons I outlines, and `capistrano-harrow` because it would be unreasonable to bump Capistrano versions every time there was a tweak in the harrow plugin.

> Harrow doesn't even have a free plan. Everyone is being pushed to use this service and pay money.

It has a free plan, and the paid plans directly support the continued work on Capistrano which supports an ever broader range of Ruby and Rails versions, not to mention countless gems, plugins and other languages and frameworks, all of which have to be tested for. I'll make sure to update the pricing page and make that clearer, I'm also surprised, you've picked up `0.4.0` which displays the following message, the first bullet point mentions that it's free:

<img width="508" alt="screenshot 2016-04-29 14 20 01" src="https://cloud.githubusercontent.com/assets/18952/14915754/931dbf98-0e15-11e6-94b1-060100e733c3.png">

> I understand that maintainers of Capistrano are allowed to do anything with their own project. I also understand that their work is of...snip...o. But the way this situation is handled is morally wrong and goes against open source principles.

If you no longer agree with the terms under which the software is made available there are plenty of options. If you examine the `capistrano-harrow` integration you'll notice it's not even *loaded* unless you are running `cap install` which happens once, and you can answer `no` to the prompt. Morally wrong is also a rather large overstatement. By your standards I might equally accuse you of expecting me to produce software for you without recompense as being morally wrong, but that's neither fair nor accurate. Please avoid personal insults when opening Github issues, it's against Github's code of conduct.

The Harrow platform is designed to help me as a maintainer better help people who are running into problems. I had to quit supporting people in IRC and StackOverflow because it's impossible to quickly help people when you can't see what environment they're working in, and you can't assume anything about what they are doing, have done, or are not doing. 

Making it commercial so that I can dedicate my working life completely to FOSS is a side effect which should lead to more, better, sustainable software for everyone in the long run.

**Comment by unfunco** [comment]
Making something commercial isn't an issue and it isn't morally wrong, the issue is that (as you have said) `capistrano-harrow` does nothing for existing users, it only provides a prompt upon `cap install`, to which one can answer no. The dependency is still installed despite the majority of existing Capistrano users not requiring or using Harrow, it's already a separate gem, it should be up to those deciding to use Harrow to add `gem 'capistrano-harrow'` to their Gemfile, if nothing else it's wasting (admittedly little) bandwidth for no real purpose for the majority of existing users.

**Comment by leehambley** [comment]
@unfunco thanks for your comments, could I ask you to join the [conversation at Hacker News](https://news.ycombinator.com/item?id=11594804)? We try and keep Github solely for issues relating to code/bugs and do user support and discussion topics on the mailing list or IRC (as much as we can) I believe many of the points you raised are addressed at HN.

**Comment by omouse** [comment]
For some users and developers, it's important that a project that's free/libre/open source only relies on non-proprietary dependencies.

It would be productive to post a short message somewhere that notes this proprietary dependency and how to remove or disable it or, preferably how to add it in.

**Comment by leehambley** [comment]
> For some users and developers, it's important that a project that's free/libre/open source only relies on non-proprietary dependencies.

Understood, you may not be aware, but last year I invested hundreds of hours to audit the code and contact every contributor who had ever contributed and performed a GPL->MIT relicensing. The `capistrano-harrow` code is also licensed under MIT and does not cause legal issues.

If you are referring to the proprietary nature of the Harrow platform, no code from Harrow is included (or ever will be) in Capistrano. Harrow is written in Go and is not compatible anyway. The gem opt-out 

> It would be productive to post a short message somewhere that notes this proprietary dependency and how to remove or disable it or, preferably how to add it in.

This is published in the Gem's (intentionally very short) `README.md`:

* https://github.com/harrowio/capistrano-harrow#opting-out 

People would have clearly seen this message when auditing their new dependencies. If you want to avoid such things in the future, you can use the `Gemfile` to lock a specific version until you have time to audit the upstream changes and see if they bring anything you need or fix any bugs you were having.

**Comment by FooBarWidget** [comment]
I have the feeling that @omouse is talking about an indirect/networked dependency on Harrow. The idea that the entire ecosystem must be entirely free/open is a copyleft philosophy. But the entire point of the MIT license (which Capistrano uses, as well as most of the Ruby/Rails ecosystem) is that it is *not* copyleft. In fact, copyleft licenses like GPL are falling out of favor because more and more people view lack of restrictions -- including a lack of restricting association with closed source -- as "more free". If @omouse wanted a copyleft ecosystem -- well, that isn't what the majority of the Ruby ecosystem is about, and apparently that's not what the majority of the community wants, or else people would have chosen AGPL or something as license.

**Comment by leehambley** [comment]
Thank you for your comments @FooBarWidget I believe that is a pretty solid way to draw a line under this thread, I'm going to lock it and encourage the conversation to continue on the HN thread [here](https://news.ycombinator.com/item?id=11594804). 

I think it's fascinating what a diverse array of opinions and expectations everyone has from open source, not least the wildly varying different degrees of "free" and how each one is superior.

I thank everyone for their input, see you at HackerNews.

**Comment by leehambley** [comment]
Edit, I'm unlocking the discussion because I don't want to stifle any useful input, but please - take it to HN :)

**Comment by jaredbeck** [comment]
The sustainability of FOSS aside, if you simply don't want to see advertising when you install gems, you might like the (unfortunately named) https://github.com/tpope/gem-shut-the-fuck-up (sorry, I didn't name it, but it does the job)

**Comment by mattbrictson** [comment]
@jaredbeck Silencing of post-install messages is also built into Bundler 1.10+: http://bundler.io/blog/2015/06/24/version-1-10-released.html#new-features

**Comment by leehambley** [comment]
@jaredbeck I think @tpope speaks for all of us when he named that Gem! Thanks for posting.

**Comment by omouse** [comment]
@FooBarWidget copyleft licenses are becoming more favourable, everyone's getting tired of the copyright regime and of companies taking code without contributing back as they do now with the MIT/BSD licenses.

It's a shame that the larger ecosystem of Ruby devs doesn't quite understand the importance of the free software philosophy and why we should resist proprietary software but that's not what this is about.

Money can be made by the devs of capistrano to support further development without resorting to proprietary licenses or to a software as a service which is also proprietary and locks customers in.
