### ISSUE TITLE
Potential breaking change: slash in :application

### ISSUE THREAD

**Issue by sagikazarmark** [capistrano/capistrano#1657]
#### Steps to reproduce

0. Have an :application name like "vendor/application"
1. Upgrade to Capistrano 3.5 (from ~3.1, which was locked to 3.4 prior to update)
2. Deploy

#### Expected behaviour

Don't know if this is expected, or a BC breaking change which should be fixed. However it is a change and I could find documentation for it.

#### Actual behaviour

Prior to 3.5 names like these worked. I've gone through the change log, the only reference I found was actually fixing a bug related to application name. Currently I get the following error:

```
The :application value "vendor/application" is invalid!
Use only letters, numbers, hyphens, dots, and underscores. For example:
  set :application, 'vendor_application'
(Backtrace restricted to imported tasks)
cap aborted!
Capistrano::ValidationError: Capistrano::ValidationError

Tasks: TOP => production
(See full trace by running task with --trace)
```

**Comment by leehambley** [comment]
Thanks for the report @sagikazarmark. What you're seeing is intentional, but I don't think we'd considered your use-case.

It looks like your app lives in a sub-directory of your Git repository, and you were relying on being able to use `/` in the name ? (Or, alternately that you set `deploy_to` on level higher than your actual servers' webroots?)

Either way we added guards to ensure that the `application_name` (which is used for a directory name) is a valid (on most platforms) directory name, hence advising against spaces and other special characters.

I'll add some labels here so others can pitch in and we can think about how to fix this.

**Comment by sagikazarmark** [comment]
> It looks like your app lives in a sub-directory of your Git repository, and you were relying on being able to use / in the name

Exactly. It was kind of a lazyness from me, but it was convenient as well.

> Either way we added guards to ensure that the application_name (which is used for a directory name) is a valid (on most platforms) directory name

Actually, I think this is a good idea, so probably the best thing to do is to document it as a breaking change (and putting your reasoning there). IMO it's not a big deal to use different names, BC is what an issue here from my POV.

**Comment by leehambley** [comment]
Closing after [updating the changelog](https://github.com/capistrano/capistrano/commit/7a3702aa6e0278ca3cef9ba801b29e87b95279b2) to reflect that this is a breaking change if you relied on the path naming to represent subdirectories.
