### ISSUE TITLE
 Support Java code release?

### ISSUE THREAD

**Issue by lgh8820** [capistrano/capistrano#1697]

**Comment by will-in-wi** [comment]
Could you expand? What kind of Java code? What does a release look like? Does it involve compiling a war file and uploading to Tomcat?

**Comment by lgh8820** [comment]
Yes, we need to compile Java code war and jar, and upload it to Tomcat.

**Comment by mattbrictson** [comment]
To my knowledge there isn't an off-the-shelf plugin for Capistrano that does that sort of WAR/JAR deployment to Tomcat. You might check Stack Overflow to see if anyone has attempted it and is willing to share.

Unless you are already invested in Capistrano, I recommend not using Capistrano for this particular scenario. It sounds like you want to build a WAR/JAR locally and then upload it. That goes against the grain of Capistrano's standard deployment flow, which is to export files directly from a source code repository to the server.

--

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).

**Comment by lgh8820** [comment]
Okay, thank you for your patience to answer, publishing tools or other code, thank you very much
