### ISSUE TITLE
 errors with postgresql 9.5

### ISSUE THREAD

**Issue by rjrobinson** [capistrano/capistrano#1712]
So, I recently upgraded my Postgres database to version 9.5. The existing app that was running connected to the database just fine. 

Its when we deployed changes that started causing issues. We kept getting 

`password authentication failed for user "new_database_name"` 

Which was really odd. The `database.yml` files were all updated.

database.yml
``` yml
---
production: 
    ...
    database: new_database_name
    username: clduser
    ...
```

We started seeing issues, where the `new_database_name` was getting inserted regardless of what we had in the database.yml 

So, after 2 days, we decided to comment out 
`# role :db, '96.0.0.0',  user: 'clduser', primary: true`
// not actual ip address

and the deploy went fine. 

so. Do we really need role :db if its separate from my web and app server? 

why would this fail?  I find this truely odd? I'm hoping its not something stupid in the pg_hba.conf file, though it might be.

Hoping that you guys can give some insight. 

Paste Capistrano's `doctor` output here (`cap <stage> doctor`): 

I have no doctor task

**Comment by mattbrictson** [comment]
Hi, welcome to the Capistrano issue tracker. This is the core Capistrano project, which has no relation to Rails or PostgreSQL. If you think you've found a bug with Capistrano's Rails deployment tasks, then you should report your issue in capistrano-rails repository, here: https://github.com/capistrano/rails

It looks to me that you have a problem with the configuration of PostgreSQL itself, or perhaps the contents of the `database.yml` on the `:db` machine. Neither of these are Capistrano-specific, so I suggest you try Stack Overflow for getting help.

> Do we really need role :db if its separate from my web and app server?

Commenting out the `:db` role means that your database migrations will not be run by capistrano-rails, so you are simply sidestepping the underyling issue. The next time you want to run migrations, you will need the `:db` role and will have to figure out your connection issues.

You can try setting the migration role to be `:app` instead. This might solve your problem if there is something wrong with the setup of the `:db` machine.

```ruby
set :migration_role, :app
```

--

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).
