### ISSUE TITLE
Silent mode is missing

### ISSUE THREAD

**Issue by Heliosmaster** [capistrano/capistrano#1749]
The `-s` (silent) option (present in at least version `3.2.1` was removed). I could not find the info in the changelog nor an explanation for it. In my particular use case, i manually log what I need so i would really like an option for it to not log anything on its own.

#### Steps to reproduce
Any capistrano command with the `-s` argument

#### Expected behaviour
Capistrano does not log stuff to stdout

#### Actual behaviour
Capistrano does not accept `-s`

#### Your configuration

N/A

**Comment by mattbrictson** [comment]
Hi, the relevant reasoning can be found in #1015.

In short, the `-s` option was removed because it never worked. Capistrano is built on top of Rake, and therefore inherits Rake's command-line options, like `-s`. But Capistrano uses its own output code that doesn't honor those flags. So we removed the flags to avoid confusion.

If you want to disable output in Capistrano, you can edit your `deploy.rb` and set this option:

```ruby
set :format, :blackhole
```
