### ISSUE TITLE
Populate deploy_to variable with custom server property

### ISSUE THREAD

**Issue by sander3** [capistrano/capistrano#1750]
I'm trying to populate the deploy_to variable with a custom server property (named organisation) to deploy the same application multiple times to the same server.

`set :deploy_to, "/home/deploy/sites/#{server.properties.organisation}"`

It seems impossible to load the server Array? using the `fetch()` method.

**Comment by mattbrictson** [comment]
Sorry, I believe this is not possible with Capistrano. The only thing I can think of is to run the `cap` command multiple times with different arguments/environment variables. You might want to post this to Stack Overflow to see if that community there has more ideas.


--

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).

**Comment by sander3** [comment]
Thank you for your comment. I'm using your idea as a workaround for now and asked the same question on Stack Overflow (http://stackoverflow.com/questions/38991846/how-to-populate-deploy-to-variable-with-custom-server-property).
