### ISSUE TITLE
Capistrano Truck Factor

### ISSUE THREAD

**Issue by 2mferreira** [capistrano/capistrano#1772]
Dear **Capistrano** contributors,

I am Master's student investigating the importance of the idea of truck factors in Software Engineering.

As you know, truck factor (aka bus factor) is defined as “the number of people on your team who have to be hit by a truck before the project is in serious trouble”. 
By "serious trouble", we mean that it will very difficult to maintain the project (e.g., bugs will take more time to be fixed, new features will be delayed etc).

I would appreciate your contribution by answering two questions:

1) According to your experience, what number best represents the truck factor of **Capistrano**?

2) Who are the developers responsible for this truck factor (i.e., the name of the developers who are responsible for the TF result answered in the previous question)?

Mívian Ferreira
Master's Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by will-in-wi** [comment]
Offhand, I'd say 2. If @mattbrictson and @leehambley got hit by the proverbial truck, Capistrano would be in serious trouble. However, you can see from https://github.com/orgs/capistrano/people that there are 5 other people who could at least give access to new maintainers or maintain it themselves.

On the other side, if only one of them disappeared, I don't know whether the project would be in very good shape. Between the two of them, the load seems manageable.

Incidentally, I usually refer to someone "winning the lottery" (which might be a uniquely American term, I don't know) as the situation in which they leave. Slightly happier than traffic fatalities. 😄 🎫 🚌 🚚

**Comment by leehambley** [comment]
> I am Master's student investigating the importance of the idea of truck factors in Software Engineering.

One of the most successful projects in the world has a de facto bus factor of one, when seen from the outside. Torvalds tries very hard to make a dictatorship (his words) which concentrates decision making weight in a very small (ideally one) number of people. 

Capistrano doesn't follow the same model, but we do make a lot of decisions "at the top" as we are more likely infrastructure where a strong opinion and stable codebase is worth more than whimsical ebbs and flows of monthly, weekly, or (*ahem* JavaScript) daily trends.

Technically speaking Matt and I own the keys to the castle but @will-in-wi is getting his copy soon enough, and there is precedent (see the death of Jim Weirich, Rubyist) of GitHub and Rubygems.org making provision for the safe continuation of projects in cases of the death, or effective death through spontaneous world-travel of their authors and maintainers.

> Incidentally, I usually refer to someone "winning the lottery" (which might be a uniquely American term, I don't know) as the situation in which they leave. Slightly happier than traffic fatalities.

I like your attitude :)

**Comment by mattbrictson** [comment]
Agreed that the "truck factor" (I much prefer the lottery analogy!) is 2 at this point, in the sense that Capistrano would *temporarily* be in "serious trouble" if @leehambley and myself both suddenly disappeared from the project.

However the strength of open source is that another person or community could pick things up where we left off. This is especially true for Capistrano because:

* We don't have any centralized secrets or infrastructure that could not be transferred to another party; in the worst case the repo could be forked and the gem renamed, ala [CanCanCan](https://github.com/CanCanCommunity/cancancan)
* Capistrano has a large network of committers that have at least passing familiarity with the code
* The project uses standard testing and release tools well-understood by Ruby devs

I hope that helps!
