### ISSUE TITLE
[Question] How to get current server host in multiple servers deployment

### ISSUE THREAD

**Issue by Lctrs** [capistrano/capistrano#1802]
Hello,

I need to deploy an application to multiple servers and adapt the deploy_to path in function of the server's hostname declared in the config.

Is there a way of achieving this ?

Below my current config for (maybe) a better understanding.

```ruby
server 'server1', user: 'deployer', roles: %w{app db web}
server 'server2', user: 'deployer', roles: %w{app db web}

set :deploy_to, '/var/www/' + fetch(:HOSTNAME) # could be server1 or server2 depending on current server we are deploying to
```

Best regards,

**Comment by mattbrictson** [comment]
Unfortunately, no. Capistrano variables are global for a particular execution of `cap deploy`, which means they cannot be adapted based on host. If you are writing custom tasks using custom variables, there are ways around this using lambdas that accept a host as an argument. But `:deploy_to` is a core part of the framework and so such customization is probably not possible.

You might check Stack Overflow to see if someone has come up with a creative workaround.


--

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).
