### ISSUE TITLE
ask function to get an option to enumerate only valid responses

### ISSUE THREAD

**Issue by chamini2** [capistrano/capistrano#1833]
I have an `ask` call that can either be one of two values, I was thinking it would be nice if such checks could be done with an `ask` option

```
ask(:country, 'what country to deploy to?', valid: ['ve', 'co'])
```

If something different of `ve` or `co` is given by the user, the task cancels.

**Comment by mattbrictson** [comment]
Thanks for the suggestion.

I think this is already possible by using Capistrano's validation feature, as documented here: http://capistranorb.com/documentation/advanced-features/validation-of-variables/

Specifically, you could write:

```ruby
ask(:country, 'what country to deploy to?')
validate :country do |key, value|
  unless %w(ve co).include?(value)
    raise Capistrano::ValidationError, 'invalid country!'
  end
end
```

Does that work for you?

**Comment by chamini2** [comment]
It does, I just thought more people could have this situation so it would be worth adding as an option.

**Comment by mattbrictson** [comment]
In my experience, `ask` is most commonly used to input things like passwords that cannot otherwise be stored in the deployment scripts. I haven't seen it used for multiple-choice conditionals. Maybe that's just me. I don't know how useful this would be to the typical Capistrano user.

Right now I don't see this as a high-priority (since a workaround exists), but I'll leave this open for discussion in case other Capistrano users would like to add in their 2¢. Thanks for the idea, though!

**Comment by will-in-wi** [comment]
I think if anyone wants to contribute a PR for this, go for it. But I don't think the maintainers intend to write this. So I'm going to close this for now. Feel free to reopen if you disagree.
