### ISSUE TITLE
execute rvm:check fails capistrano

### ISSUE THREAD

**Issue by hashmee** [capistrano/capistrano#1850]
$ cap production deploy --trace
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rvm:hook (first_time)
** Execute rvm:hook
** Invoke rvm:check (first_time)
** Execute rvm:check
cap aborted!
Net::SSH::AuthenticationFailed: Authentication failed for user deploy@35.166.106.106
/home/hashmi/.rvm/gems/ruby-2.4.0/bundler/gems/net-ssh-ecc40c7cdea0/lib/net/ssh.rb:250:in `start'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/connection_pool.rb:59:in `call'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/connection_pool.rb:59:in `with'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/netssh.rb:155:in `with_ssh'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/netssh.rb:108:in `execute_command'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:141:in `block in create_command_and_execute'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:141:in `tap'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:141:in `create_command_and_execute'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:60:in `capture'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/capistrano-rvm-0.1.2/lib/capistrano/tasks/rvm.rake:9:in `block (3 levels) in <top (required)>'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:29:in `run'
/home/hashmi/.rvm/gems/ruby-2.4.0/gems/sshkit-1.12.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => rvm:check

**Comment by mikegee** [comment]
Are you sure this is Capistrano's fault? It looks like the connection failed to authenticate:

```
Authentication failed for user deploy@35.166.106.106
```

Try `ssh deploy@35.166.106.106` to debug.

**Comment by mattbrictson** [comment]
Hi, I recommend checking the Capistrano documentation here:

http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/

Also, @mikegee makes a good point: check that normal `ssh` works.

If you are still stuck, a good place to get help is Stack Overflow. Include output of `cap production doctor` in your question to give more context. Good luck!

---

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).
