### ISSUE TITLE
compile assets is not the same

### ISSUE THREAD

**Issue by KonishiLee** [capistrano/capistrano#1863]
There is a question when i cap production deploy for three servers, the application-xxxx.js is not the same, other two servers is same , anther one is different. please tell me how to fix it.

**Comment by mattbrictson** [comment]
Hi, sorry to hear to you are running into problems. To get help for something like this, I recommend posting your question on Stack Overflow. You will need to provide much more detail about how exactly the JS files differ, what troubleshooting you have already tried, logging output, and a description of your servers. The `cap production doctor` command can also provide useful data. Good luck!

--

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).

**Comment by KonishiLee** [comment]
Thank u so much to anwser my question.
