### ISSUE TITLE
Protect mounted points when cleaning up

### ISSUE THREAD

**Issue by kfrapin** [capistrano/capistrano#1873]
Do you think it will be interesting to have a capistrano option to protect the deletion of mounted points?

Let me give you a scenario:
  - You have a deploy task which is in charge to mount a distant directory (like a nas)  into the current release directory
  - You may have a task for umounting that folder in the previous release when deploying a new release
  - If the task for umounting failed your mount point may stay in place
  - When capistrano clean the old releases (regarding to `:keep_releases`), it executes a `rm -rf` on the previous releases folders risking to delete all the data contained into your mount point

So my question is : do you think it will be interesting to have an option like `:rm_one_file_system`  similar to the `rm` option `--one-file-system` (http://www.gnu.org/software/coreutils/manual/html_node/rm-invocation.html#rm-invocation)

I could work on it, if you are interested by this kind of option

**Comment by leehambley** [comment]
I don't know how much of a problem this is in the wild. Capistrano has been around 8 years and it's never come up so far, however NFS just won't go away, so anything is possible :)

What's always important to remember is that we could simply add the `--one-file-system` option to `rm` but it should be protected by a feature flag. We really don't like config flags because they're all in a flat namespace, and we have to be very careful about what options we make the defaults.

I'd just like to ask, but have you been able to work around this by patching the implementation of the task that removes the old releases to solve your own use-case already?

I don't *really* know if this needs to be in the cap core, if you have a working workaround.

Other maintainers?

**Comment by mattbrictson** [comment]
This sounds like the perfect use case for the [command map](https://github.com/capistrano/sshkit#the-command-map). Could you add an entry to the map for `:rm` to add the `--one-file-system` flag?

**Comment by kfrapin** [comment]
@leehambley yes, you're right about the multiple implementations, and a simple patch do the trick.  not sure this option has it place into the capistrano core

@mattbrictson this way seems to be the good one, but I don't really see how to use the `map` command, the documentation indicates how to add prefix, but not an option

should I do something like this : `SSHKit.config.command_map[:rm] = "rm --one-file-system"` in one of the capistrano config file?

**Comment by mattbrictson** [comment]
> should I do something like this : `SSHKit.config.command_map[:rm] = "rm --one-file-system"` in one of the capistrano config file?

Yes, exactly. Put that in your `deploy.rb`.

**Comment by kfrapin** [comment]
I will give it a try and let you know if it works properly  ;)

**Comment by kfrapin** [comment]
Yes the addition of `SSHKit.config.command_map[:rm] = "rm --one-file-system"` in the `deploy.rb` file do the trick :)

When deploying I can see the remotely executed command : 
```
[...]
01 rm --one-file-system -rf ...
[...]
```

And if a mounted point is still in place, it will be skipped by the `rm` command

Thanks for your help!
