### ISSUE TITLE
[Question] Passing array as an argument to a custom built before/after hook task

### ISSUE THREAD

**Issue by BentCoder** [capistrano/capistrano#1877]
Hi,

I've seen example below on web but wasn't able to get answers for some questions so I'm afraid I'll have to bother you guys. I do apologise for it though! My background with ruby and capistrano is about 3 days.

Thanks

- What does `second_param` do?
- Why does output contain `command`?
- How can I simplify the example? My aim is simple: pass an array argument to task and loop through it. Maybe this example is doing little too much.

```
before "deploy:starting", :second_param do
  invoke 'task:invoke', ['arg1', 'arg2']
end

namespace :task do
  task :invoke, :command do |task, args|
    on roles(:app) do
      args.each { |x| puts x }
    end
  end
end
```

```
$ bundle exec cap staging deploy
command
arg1
arg2
```

**Comment by will-in-wi** [comment]
Without a lot more specifics, it's quite difficult to answer your question. I'd suggest reading about how Rake works, and how Capistrano works in the documentation. If you need further help, a specific example would be easier to answer.

---

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).
