### ISSUE TITLE
Provide config for timezone of release timestamp

### ISSUE THREAD

**Issue by yskkin** [capistrano/capistrano#1878]
Directory names under `release_path` is formatted in UTC.
It would be better if we have config for changing timezone like `set :release_timestamp_zone, "+09:00"` since that makes manual administrative tasks more intuitive.

# Current workaround

```
task :fix_timestamp do
  env.instance_variable_set(:@timestamp, Time.now)
end
after :"load:defaults", :fix_timestamp
```

**Comment by yskkin** [comment]
I'm ready for opening up a PR if this is avaiable :smile:

**Comment by leehambley** [comment]
I'm opposed to introducing new top-level configuration variables. This is an elegant workaround however.

**Comment by yskkin** [comment]
Thank you for your response.
I thought top-level configration was OK since this is going a same way as #1818.

Is exposing timestamp setter OK for you?
Then I can write `Capfile` like this:

```
require "capistrano/setup"
require "capistrano/deploy"
Capistrano::Configuration.env.timestamp = Time.now
```

**Comment by mattbrictson** [comment]
I think UTC is the right thing to do here, so I am not really motivated to add time zone as a configuration option to Capistrano itself. It looks like you already have a good workaround, so I am inclined to close this issue.

Just curious, though, could explain more about your use of the `release_path`? What sort of manual administration tasks use this file? Perhaps there is another feature hiding in your use case.

**Comment by yskkin** [comment]
I understand that we don't need a config for timezone.
But please consider adding `attr_writer :timestamp` to `configration.rb` so that I can write `env.timestamp = Time.now`.

As for my use case, I need to check when deployment is done from `revisions.log`
in order to investigate regression or check last deployment time to judge which commit is deployed and which is not.
Local time is more comfortable for my environment than commit hash.

**Comment by leehambley** [comment]
Using your workaround (and not making the [timestamp](https://github.com/capistrano/capistrano/blob/7ba6e446ff4f517814d8e5a79710aa122a8b9064/lib/capistrano/configuration.rb#L109-L111) makes me more comfortable. 

Exposing it as part of the "public" api encourages its use, whereas relying on Ruby's dynamic properties to workaround this is feel is a clear enough signal that we can't recommend people do this!

**Comment by yskkin** [comment]
I understand. Thank you for clarification.

**Comment by jsonUK** [comment]
I know this is closed, but I wanted to comment: I think you should reconsider making it a config option.

I'm sure many have probably searched this question and come to this page; Seeing timestamps that aren't related to a developers/sys admins timezone is annoying.

I can see why you would like to keep UTC for teams that operate globally, but that should be a team decision - companies or individuals who operate in the same location should be able to override the timezone from the default UTC.

Please reconsider making it a new option, so that nobody has to rely on a hack/fix. Thanks

I've used Capistrano for a very long time and still think it's a great deployment tool.

# FYI, How to change the timezone
Paste the code snippet to the bottom of you **Capfile** to make it work.
