### ISSUE TITLE
Unable to reference staging variables in deploy.rb

### ISSUE THREAD

**Issue by BentCoder** [capistrano/capistrano#1879]
I wonder if this is a bug!

I'm unable to reference `stage_artifacts` variable of "staging.rb" from within "deploy.rb" with `*fetch(:stage_artifacts)`. However, if I define `stage_artifacts` in "deploy.rb" itself then I can reference to it as well as within "deploy/tasks/my.rake" file.

```
$ cap -v
Capistrano Version: 3.8.0 (Rake Version: 12.0.0)
```

**Capfile**

```
set :deploy_config_path, "deploy/deploy.rb"
set :stage_config_path, "deploy/stages"
....
Dir.glob('deploy/tasks/*.rake').each { |r| import r }
```

**deploy/deploy.rb**
```
....
set :artifacts, [
    "parameters_#{fetch(:stage)}.yml.dist",
    "config_dev.yml",
    "app_dev.php"
    ].push(*fetch(:stage_artifacts))

before "deploy:starting", "my:artifact:clean"
```

**deploy/stages/staging.rb**
```
....
set :stage_artifacts, ["config_prod.yml"]
```

**Comment by mattbrictson** [comment]
Hi, thanks for the report!

This is not a bug. It is by design that `deploy.rb` is loaded first, and then your selected stage file is loaded second to *override* your deploy.rb with stage-specific values.

Perhaps you'd be better served with a pattern like this:

```ruby
# deploy.rb
set :artifacts, ["my", "default", "artifacts"]

# staging.rb
append :artifacts, "custom"
```

In other words, set a default value for `:artifacts` in `deploy.rb`, and then you can append to it in `staging.rb`.

Hope that helps!

**Comment by BentCoder** [comment]
Got it and it works perfectly fine. Thanks.
