### ISSUE TITLE
Capistrano should "just work" for git and installed gems with no extra Capfile configuration

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1880]
@robd made an interesting suggestion in https://github.com/capistrano/capistrano/issues/1824#issuecomment-294432884, which I am pasting below. Let's use this thread to discuss this idea specifically, as well as the more general notion that Capistrano should do more "out of the box" instead of requiring explicit configuration.

/cc @will-in-wi @leehambley 

---

FWIW, I think that making people choose the scm they are using seems like a step in the wrong direction. I know there was a lot of chat about this and I wasn't involved, but it feels to me like this is making our lives as maintainers easier (I guess that's why we're making the change?) at the expense of convenience for the users.

The more we add to the Capfile, the more people like me will get it wrong by putting it in the wrong place, making typos, referring to out of date docs saying the wrong thing, version incompatibilities, etc etc.

Personally, I have a different take on what we should do. I would like to see all of the following removed from the Capfile:

```ruby
require 'capistrano/setup'
require 'capistrano/deploy'

require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

require 'capistrano/rails'
```

This way there is no risk of a user messing this stuff up.

My hunch is that the majority of users are git and rails users, so my opinion is we should have some way of the plugin system working out the following:

1. it's git because there is a .git repo
2. deploy & rails are needed because I installed the capistrano-rails gem

**Comment by mattbrictson** [comment]
Related: 

https://github.com/capistrano/capistrano/issues/1651 Feature: `cap install` should pre-populate deploy.rb :repo_url, if .git repo is detected

**Comment by robd** [comment]
@mattbrictson Thanks very much for raising this. 

I don't know the ins and outs of it, but my gut feel is that for a given project there is only one 'correct' set of Capfile lines and order they should be included in. Do you think that's correct? Are there common cases where, for example people would want more then one SCM to be included? Or where people would want to include `capistrano/deploy` without including `capistrano/setup` or where they need to do something between `capistrano/deploy` and `capistrano/setup`, or after `capistrano/deploy` before `capistrano/scm/git`?

If the majority of people are just using the default generated Capfile, moving the config into the  users' Capfiles has a couple of disadvantages to my mind:

  1) It means that people might specify things in the wrong order and we have to spend time supporting these issues.
  2) It means if we come up with improvements or need to fix bugs which necessitate changing the line order, inserting a new line in-between the existing ones, renaming files, etc we're into the business of trying to rewrite peoples' Capfiles or explaining people how to make those changes.

I realise this is probably a lot of work and I don't understand the bootstrapping process well enough to know if we could easily detect a Capfile with no `require` or `install_plugin` lines in it and try to autoload the things they'll need. Perhaps autoloading these things is sufficiently complex (eg because there are so many combinations of plugins etc that people are using) that we wouldn't be able to reliably achieve it for a large long tail of users.

**Comment by mattbrictson** [comment]
I don't want to shoot down the idea of auto-loading plugins, because I think simplifying things for the users is a good goal. But here are the challenges that I think we would run into:

1. Just because a gem is installed on my system doesn't necessarily mean I want to load it. I may use Capistrano for two different projects, each requiring a different subset of gems.
2. How will Capistrano know which gems to `require`? Will it simply load every gem named `capistrano-*`?
3. What if I want to customize the standard Git plugin by subclassing it? That means I want to `require` it but I don't want to "install" it. (This is what motivated a separate `install_plugin` step).
4. It is becoming more common to deploy Rails without the asset pipeline (e.g. API-only apps). In this case I have the `capistrano-rails` gem installed, but I don't want to require the whole thing (assets + migrations); I just want the `capistrano/rails/migrations` part.
5. If I use a Gemfile, and Capistrano auto-detects configuration based on gems, then I will get vastly different behavior depending on whether I run `cap deploy` vs `bundle exec cap deploy`, which can be dangerous/confusing.

This is not to say that these issues are insurmountable, but they are things to consider.

---

We could do something less ambitious, like auto-detecting and loading the appropriate SCM based on the presence of e.g. a `.git` directory so that the user doesn't have to explicitly specify it in the Capfile. There just needs to be a way to "opt out" of this behavior for people who want to use a custom SCM implementation.

**Comment by robd** [comment]
Thanks very much for providing this input. I certainly hadn't thought through any of these cases and I imagine that there is a very long tail of people using Capistrano in unusual ways. 

I agree that detecting which Gems are loaded at runtime would be too dangerous. One option might be for a user to specify a Gemfile from which to load the dependencies, or autodetect a Gemfile in the same directory as the Capfile. Maybe this is too magic. As for which gems to require, I guess I was just thinking about detecting the ones which are currently listed in the readme, but again maybe this is too magic as well.

As for the main capistrano setup lines:
```
require 'capistrano/setup'
require 'capistrano/deploy'

require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
```

One option would just to be to combine these into a single file, along with some SCM detection stuff. eg:

```require 'capistrano/auto_setup'```

or even re purpose the existing 'deploy' file and deprecate calling `require 'capistrano/setup'` separately before it:

```require 'capistrano/deploy'```

The latter solution would have the advantage that many people who didn't upgrade to 3.7 would never need to add the manual scm related lines. I guess at the moment, the scm plugins are dependant on, and mainly to support the stuff in`require 'capistrano/deploy'` and no one can use the scm plugins with `require 'capistrano/setup'` only. Am I right about this?

My hunch is that detecting the SCM plugin automatically somehow (eg via .git detection) would be helpful to a lot of people. However there are some disadvantages of this:

1) We would have to put knowledge of the main SCM plugins in the Capistrano rather than just in comments
2) I don't know how hard it is to know which scm is in use on a particular project
3) If the require / install_plugin lines ever changed then we would have to support multiple versions

For people who wanted to do something customised, they could inline the `auto_setup` (or `setup`) file into their Capfile, ditch the bits they didn't want etc.

I'm not sure if these suggestions are feasible, but hopefully this is of some help.

**Comment by will-in-wi** [comment]
Just as a thought, I used to have a Capistrano deployed repo using SVN which I used the Git client to interact with. This isn't an especially uncommon workflow.

**Comment by robd** [comment]
@will-in-wi This is an interesting use case. Just to make sure I understand - do you mean that if we detected a .git directory and added the git SCM plugin, this would be incorrect for you because you need the svn one?

I have no idea what percentage of people are set up in this mode. Do you have a feel for if it's 1 in 10 or 1 in 100?

**Comment by will-in-wi** [comment]
That would be correct, however I'm guessing it's closer to 1 in 100,000. It's just an extreme edge case. Not many people use Capistrano with SVN anymore.

**Comment by mattbrictson** [comment]
So far I don't think the changes that have been suggested are compelling enough. If we make things easier for users in this case we are simply moving complexity elsewhere (e.g. into `capistrano/auto_setup`). My gut feeling is that managing the transition and maintaining backwards-compatibility will be hard.

In retrospect, perhaps the SCM changes in 3.7 were too drastic for a project of Capistrano's maturity and user base.

But I don't think that the solution is even more code changes. Personally, I think that the time and effort would be much better invested in improving Capistrano's documentation, as that seems to be the biggest sore spot right now and would benefit the most people.

Also, I am certainly biased, but I think the problem with the 3.7 SCM system is overstated. Since most people probably use Git, and most do not change their SCM mid-project, Capistrano will work perfectly out of the box with the [default Capfile](https://github.com/capistrano/capistrano/blob/7ba6e446ff4f517814d8e5a79710aa122a8b9064/lib/capistrano/templates/Capfile) generated by `cap install`. Existing users upgrading to 3.7 will have to get over a one time speed bump of modifying their Capfile, but the [upgrade doc](https://github.com/capistrano/capistrano/blob/7ba6e446ff4f517814d8e5a79710aa122a8b9064/UPGRADING-3.7.md) walks them through it, and we've [fixed the deprecation warning](https://github.com/capistrano/capistrano/pull/1882) to make the explanation more explicit. Once the upgrade is done, they have nothing more to worry about.

If there are small things we can do to smooth the upgrade, let's do it, but I think overhauling the Capistrano boot process is going a little far, IMHO.

**Comment by deivid-rodriguez** [comment]
Hi! Sorry if this is not the right place to ask for this, but... How should plugins catch up with this change? I just realized that [capistrano-pending](https://github.com/a2ikm/capistrano-pending) broke for me after I upgraded to 3.7 and removed the `:scm` setting, since the setting is used [here](https://github.com/a2ikm/capistrano-pending/blob/master/lib/capistrano/pending/tasks/pending.rake#L12).

Thanks!

**Comment by mattbrictson** [comment]
@deivid-rodriguez sorry, I am not familiar with capistrano-pending. I suggest opening an issue in that repo and hopefully the author or current maintainer can take it from there.

**Comment by deivid-rodriguez** [comment]
The plugin seems a bit abandoned so I was hoping to get some clue so I can provide a PR. Anyways, done: https://github.com/a2ikm/capistrano-pending/issues/7. Thanks!

**Comment by robd** [comment]
@mattbrictson Thanks for taking the time to discuss this stuff. It doesn't sound like there is anything else to do here at this stage, so closing.
