### ISSUE TITLE
configuration instructions regarding to migration impedes deployment in logical loop 

### ISSUE THREAD

**Issue by dvodvo** [capistrano/capistrano#1908]
Gemfile includes
`gem 'capistrano', '3.4'`
`gem 'capistrano-bundler', '~> 1.1.2'`
`gem 'capistrano-rails', '~> 1.1.1'`
`gem 'capistrano-rbenv', '~> 2.0'`

When deploy is set in deploy.rb as
`lock '3.8.1'`  (lower versions complain that capistrano version is higher than the lock version) 
`# Default value for :scm is :git`
`set :scm, :git`
`# require "capistrano/scm/git"`
`# install_plugin Capistrano::SCM::Git`
deployment is halted with the following:
`[Deprecation Notice]            set :scm, :git         is deprecated.
To ensure your project is compatible with future versions of Capistrano,
remove the :scm setting and instead add these lines to your Capfile:`

`    require "capistrano/scm/git"`
 `   install_plugin Capistrano::SCM::Git`

Edit to 
`# set :scm, :git`
`require "capistrano/scm/git"`
`install_plugin Capistrano::SCM::Git`
deployment is aborted:
`WARNING: load:defaults has already been invoked and can no longer be modified.
Check that you haven't loaded a Capistrano plugin in deploy.rb by mistake.
Plugins must be loaded in the Capfile to initialize properly.
(Backtrace restricted to imported tasks)
cap aborted!`
(this warning pops up if all three lines are uncommented)

OK...  Attempt
`# set :scm, :git`
`require "capistrano/scm/git"`
`# install_plugin Capistrano::SCM::Git`
deployment halts with the first error messge (almost):
`[Deprecation Notice] Future versions of Capistrano will not load the Git SCM
plugin by default. To silence this deprecation warning, add the following to
your Capfile:`

`    require "capistrano/scm/git"`
`    install_plugin Capistrano::SCM::Git`

So what is it?  Applications are NOT deployable in this context.

**Comment by mattbrictson** [comment]
Hi, sorry to hear you are running into trouble on this.

First of all, I see you have `lock '3.8.1'`, but a Gemfile with `gem 'capistrano', '3.4'`. This tells me that you are not executing Capistrano correctly. If you intend to use v3.4 as indicated in your Gemfile, then the correct way to invoke Capistrano is:

```
bundle exec cap
```

This will ensure that the version number in your Gemfile is honored.

---

Otherwise, if you'd like to use v3.8.1, then you will need to upgrade your Capfile as indicated by the deprecation warning message. The rest of my reply is concerning this upgrade process.

If I am understanding correctly, you saw the SCM deprecation warning and then edited your `deploy.rb` to contain:

```ruby
# deploy.rb
lock '3.8.1'
# set :scm, :git
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
```

Again, maybe I misread. But the warning message says that the lines should be added to the `Capfile`, not `deploy.rb`. Therefore the correct setup is to edit the **Capfile** as follows:

```ruby
# Capfile
require "capistrano/setup"
require "capistrano/deploy"
# ...
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
```

Do *not* use `require` or `install_plugin` in `deploy.rb`.

Let us know if that resolves it, or please correct me if I've misunderstood your issue.

**Comment by dvodvo** [comment]
I confirm that it resolves the problem. But inefficiently. deploys talking 1:41 minutes have balooned to 4:00 - not nice for angsty devs...  Order of items in capfile has been a issue I have tripped over in the past.  Could this impact matters here?

**Comment by mattbrictson** [comment]
What part of the solution is inefficient? If you are running into a performance issue and you can narrow it down to a specific Capistrano version upgrade or configuration change that triggered the regression, could you please open an issue with the details? That would be much appreciated.

If the original issue has been resolved, can I close this issue?

**Comment by dvodvo** [comment]
Yes, this issue is to be closed.
