### ISSUE TITLE
The deploy has failed with an error: undefined local variable or method `strategy' for #<SSHKit::Backend::Local:0x00000001701100>

### ISSUE THREAD

**Issue by ethicalmohit** [capistrano/capistrano#1950]
Getting error while deploying with capistrano 3.10.0.

---

### Steps to reproduce
cap dev deploy

https://gist.github.com/ethicalmohit/b521e05bedd46a897fa04c2b2995ad23

### Expected behavior
Deployment success message

### Actual behavior
(Backtrace restricted to imported tasks)
cap aborted!
NameError: undefined local variable or method `strategy' for #<SSHKit::Backend::Local:0x00000001701100>

Tasks: TOP => deploy:tag
(See full trace by running task with --trace)
The deploy has failed with an error: undefined local variable or method `strategy' for #<SSHKit::Backend::Local:0x00000001701100>

** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:

### System configuration
https://gist.github.com/ethicalmohit/6fcba0848df62ac665ee9bad24c3cc17

**Comment by mattbrictson** [comment]
Looking at the gist you posted, the error is coming from the `cap-deploy-tagger` gem:

```
NameError: undefined local variable or method `strategy' for #<SSHKit::Backend::Local:0x000000039e3038>
/var/lib/jenkins/.rvm/gems/ruby-2.3.0/gems/cap-deploy-tagger-0.2.0/lib/cap-deploy-tagger/tasks/tagger.rake:12:in `block (3 levels) in <top (required)>'
```

That gem is apparently incompatible with recent versions of Capistrano. There is a pull request open to fix it: https://github.com/forward3d/cap-deploy-tagger/pull/8

You may have to fork the gem or find an alternative, because it looks like `cap-deploy-tagger` hasn't been touched in almost 3 years.

I'm closing this issue because this is a bug in a third-party gem, not Capistrano itself.

**Comment by ethicalmohit** [comment]
@mattbrictson can you help me to load/use capistrano 3.4.1 and lock the same? Because I am getting issue all versions above 3.4.1.
