### ISSUE TITLE
Linked file composer.lock does not exist on IP

### ISSUE THREAD

**Issue by theone26424** [capistrano/capistrano#1951]
I don't know what I did wrong, but why the composer.lock file doesn't exist? I added it to the linked_files. Please refer to my stackoverflow question below:

https://stackoverflow.com/questions/47245392/capistrano-linked-file-composer-lock-does-not-exist-on-ip

**Comment by mattbrictson** [comment]
Hi, you may also want to check this repository, which is more relevant to your issue: https://github.com/capistrano/composer. Good luck!

---

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).
