### ISSUE TITLE
top level `include Capistrano::DSL` in "lib/capistrano/setup.rb" pollutes every object

### ISSUE THREAD

**Issue by bughit** [capistrano/capistrano#2045]
Is it necessary to inject the dsl into every object? I can't give repro directions yet but I found a scenario where haml template compilation ends up calling into the capistrano dsl `on` method due to this:

https://github.com/judofyr/temple/blob/master/lib/temple/mixins/dispatcher.rb#L73

They are expecting all `/^on(_[a-zA-Z0-9]+)*$/` methods on their objects to be theirs, an assumption that capi dsl inclusion in Object violates. Arguably they should be more careful but the DSL does not need to be in every object either.

**Comment by mattbrictson** [comment]
The globally-injected DSL is pretty fundamental to the current design of Capistrano. To "protect" your app from this, use `require: false` in the Gemfile all the Capistrano gems, as suggested by the installation instructions; i.e.

```ruby
group :development do
  gem "capistrano", "~> 3.11", require: false
end
```

This ensures that both:

1. Capistrano is only installed in `:development`, so there is no risk of it wreaking havoc in your production app; and
2. The Capistrano DSL is only loaded when you explicitly require it; i.e. when you run `cap` as a command-line process. It won't be loaded in the Rails app itself.

**Comment by bughit** [comment]
The haml compilation I referred to was being done in a capistrano task. Tasks are supposed be containers of arbitrary code, that's the point of extensibility, but if you pollute Object you increase the chances of that arbitrary code breaking, so it's not a good design. Rake on which capistrano is based does not pollute Object.

**Comment by leehambley** [comment]
Perhaps you could try to prepare a patch, maybe something using refinements would work so that we can isolate the changes.

After 7 years on this architecture nobody has brought this up before, but if it's important for you, we would definitely entertain looking at a refinements (or similar) based solution. 

Refinements came in in Ruby 2.4 (2016) and although we do commit to [supporting older ruby versions](https://github.com/capistrano/capistrano/blob/master/.travis.yml#L6-L9), maybe we could re-evaluate if presented with a compelling alternative.
