### ISSUE TITLE
Capistrano can't find rake, but same command works over SSH

### ISSUE THREAD

**Issue by asfarley** [capistrano/capistrano#2077]
First off, I have to admit: I've been spamming this problem all over the place, including the [rbenv repo](https://github.com/rbenv/rbenv/issues/1304), [serverfault](https://serverfault.com/questions/1052732/why-is-bundler-failing-to-find-rake-while-deploying-with-capistrano), and [reddit](https://www.reddit.com/r/rails/comments/leu14x/why_is_bundler_failing_to_find_rake_in_my/). Due to the wide variety of responses, and the number of pieces involved, I'm not sure which component is misbehaving.

Basically, my issue is that the **deploy:assets:precompile is failing**. Capistrano output:

```
00:10 deploy:assets:precompile
      01 /home/deploy/.rbenv/bin/rbenv exec bundle exec rake assets:precompile
      01 bundler: failed to load command: rake (/var/www/framelinker/shared/bundle/ruby/2.6.0/bin/rake)
```

I've confirmed that I can execute this step manually over SSH, so this appears to be some environment-related issue where Capistrano is unable to find rake but an interactive login shell is able to find it. 

Can someone walk me through how to diagnose this?

This issue came up after upgrading my server from Ubuntu 18.04 to Ubuntu 20.04. I am using ruby 2.6.1, my Gemfile.lock has bundler 2.2.6, config/deploy.rb has:

`lock '~> 3.15.0'`

**Comment by leehambley** [comment]
https://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/

This is the standard place to look for information on this. Of course you know at least a bit about interactive and login shells, from what you wrote, but Capistrano doesn't use either interactive or (usually) login shells.

Some Linux distros give you a login shell even when they maybe shoulnd't. I suggest you follow the troubleshooting steps there. 

RVM (or rbenv) are similarly *require* an interactive login shell (usually), unless you have tooling support such as https://github.com/capistrano/rbenv

In the end, the problem is probably that you're using the wrong ruby, and thus the wrong gems, and nothing is executing in the environment you expect.

Closing this, but if you suspect a bug please, let us know, I strongly suspect however that it's just incomplete configuration on your side.

**Comment by asfarley** [comment]
No, I don't suspect a bug, but I am using `capistrano/rbenv`. I will try asking the same question in the 'capistrano/rbenv' repo.

**Comment by asfarley** [comment]
Logging into the server and manually executing the following fixed/gave me a workaround for this issue:

`/home/deploy/.rbenv/bin/rbenv exec gem update --system`

**Comment by claptimes5** [comment]
@leehambley We've been using Capistrano for years with the same config and just updated to 3.15.0 and had this exact same issue with rake not being found. Tried `gem update --system` as @asfarley recommended and had no luck. Reverting to 3.14.1 fixes this problem.

**Comment by mattbrictson** [comment]
@claptimes5 Thanks for being a long-time cap user! I don't doubt that you are running into this problem but I cannot determine any way that purely upgrading only capistrano from 3.14.1 to 3.15.0 could cause this. Here is the exact diff for those two versions that were published to rubygems:

https://my.diffend.io/gems/capistrano/3.14.1/3.15.0

I don't see anything that could be related? All 3.15.0 does is an extremely minor change to the git tasks. No other code was touched. Unless `require "securerandom"` has a side effect I am not aware of? (It would not be the first time Ruby surprised me!)

Did something else change in your setup beside just the capistrano version bump?

There have been some recent bugs in bundler that could cause the error, see:

https://github.com/search?q=bundler+%22failed+to+load+command%22+repo%3Arubygems%2Frubygems+created%3A%3E2021-01-01+state%3Aopen&type=Issues&ref=advsearch&l=&l=

And since bundler is now included with rubygems and with ruby installations in addition to be installable separately, it can be hard to know exactly what version(s) of bundler you have installed.

Bundler has a very surprising feature where it will automatically re-execute a different version of itself to match the BUNDLED WITH version in your Gemfile.lock. So if you changed the BUNDLED WITH line when you upgraded capistrano, you could have inadvertently caused a different version of bundler to execute at deploy as a result. That could explain the change in behavior.

**Comment by claptimes5** [comment]
@mattbrictson Thank you for your reply! I'll look into this more tomorrow. I don't think anything else changed, but you're right that there shouldn't be a difference (looking at the diff). Curious to hear if anyone else has this issue.

**Comment by claptimes5** [comment]
@mattbrictson just following up, looks like it was a config issue on our end. Related to a merge conflict in our Gemfile.lock. 

Thanks again for your help!
