### ISSUE TITLE
New bug when nearing end of deployment

### ISSUE THREAD

**Issue by RailsCod3rFuture** [capistrano/capistrano#2087]
Observed behavior
`01 sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an a…
`

Expected behavior
Successful deployment

I don't know why this happening - before, I had no issues with deploying to my server.

**Comment by leehambley** [comment]
In the issue template that you ignored when you opened the issue are some troubleshooting tips. As you can see you have a problem that `sudo` is being invoked in a context where it cannot ask you from a password, googling this error message will indicate that a) this is clearly a Linux configuration setting, and not a Capistrano problem, and b) that there are a multitude of ways you may overcome this, ways which we cannot advise you on because we are unfamiliar with your particular or environment.
