### ISSUE TITLE
Create symlinks atomically (The current "rm && ln -s" is NOT atomic)

### ISSUE THREAD

**Issue by eivindhagen** [capistrano/capistrano#346]
I see this pattern in several places, e.g.

```
run "rm -f #{current_path} && ln -s #{latest_release} #{current_path}"
```

this could be replaced with a single command:

```
run "ln -fs #{latest_release} #{current_path}"
```

or even better, it could use "ln -s && mv" for a truly atomic operation:

```
run "ln -s #{latest_release} #{current_path}.tmp && mv -f #{current_path}.tmp #{current_path}"
```

Has this been suggested before? I could not find any issues mentioning this. I'd be happy to create a pull-request if people agree that this is an improvement.

**Comment by frankboris** [comment]
02 The compiled services file has been removed.
    ✔ 02 ftpmbs102841@80.74.149.6 2.642s
01:41 deploy:set_permissions:acl
      01 setfacl -Rn -m u:www-data:rwX -m u:ftpmbs102841:rwX /test-deploy/releases/20180717131046/bootstrap/cache /test-deploy/releases/20180717131046/storage /test-deploy/shared/storage/app /test-deploy/releases/2…

      01 /usr/bin/env: setfacl
      01 : No such file or directory
#<Thread:0x00000000068edf40@C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as ftpmbs102841@80.74.149.6: setfacl exit status: 127 (SSH
Kit::Runner::ExecuteError)
setfacl stdout: Nothing written
setfacl stderr: /usr/bin/env: setfacl: No such file or directory
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ftpmbs102841@80.74.149.6: setfacl exit status: 127
setfacl stdout: Nothing written
setfacl stderr: /usr/bin/env: setfacl: No such file or directory


Caused by:
SSHKit::Command::Failed: setfacl exit status: 127
setfacl stdout: Nothing written
setfacl stderr: /usr/bin/env: setfacl: No such file or directory

Tasks: TOP => deploy:updated => deploy:set_permissions:acl
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as ftpmbs102841@80.74.149.6: setfacl exit status: 127
setfacl stdout: Nothing written
setfacl stderr: /usr/bin/env: setfacl: No such file or directory


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:
