### ISSUE TITLE
Use svn switch instead of svn update for cached_copy

### ISSUE THREAD

**Issue by iGEL** [capistrano/capistrano#40]
If using the cached_copy, capistrano issues a svn update command, if a cached copy is available. But if you switch the branch or tag, that command won't do anything useful. If you use svn switch, it'll switch to the new repo location (if necessary) AND update to the given revision. So there is no downside in using svn switch instead svn update.

**Comment by NoICE** [comment]
I see that in 2.12.0, 2.14.2 this issue still exists. Is that correct? All those use just svn switch bot not svn update, resulting in a small headache trying to figure out what was bundler talking about, when it said that my gemspecs changed :)

**Comment by leehambley** [comment]
I'd just like to draw your attention to our announcement on 23-10-2017 - 

- https://github.com/capistrano/capistrano/blob/master/CHANGELOG.md#3100-2017-10-23

> As of this release, version 2.x of Capistrano is officially End of Life. No further releases of 2.x series are planned, and pull requests against 2.x are no longer accepted. The maintainers encourage you to upgrade to 3.x if possible.

This issue you're commenting on is nearly 7 years old! We'd be glad to help you upgrade to a none-EOL version of Capistrano, catch us on the mailing list, and/or our guides/etc!

**Comment by NoICE** [comment]
@leehambley thank you for your quick reply, I just wanted to know / to let others know if this is indeed fixed in versions mentioned here :-)

I just have some old projects (tons of them) which each use some old version of Capistrano and these legacy projects are not actively maintained anymore and I had to just redeploy two of them. I moved some of these projects to git, which solved this issue. I use Capistrano 3 in newer projects, but don't have resources to migrate all those projects to newer one. That's my fault though...
