### ISSUE TITLE
support Rails app in a subdirectory of release_path

### ISSUE THREAD

**Issue by aspiers** [capistrano/capistrano#615]
My Rails app's root is a subdirectory underneath the `release_path`, which breaks certain default Capistrano tasks, including most (all?) of the asset-related tasks.

Presumably it would be easy to introduce a new `rails_root` variable which defaults to `release_path` but can be set by the user?  If so, let me know and maybe I'll find time to send a pull request.

**Comment by jameswangz** [comment]
I configured the app_subdir in deploy.rb like this

`set :app_subdir, '/ios/source/symbolication-server'`

my project structure is

-- project root
---- ios
-------- source
---------- symbolication-server(the rails app)

 but it seems the "bundle install" command fails due to the Gemfile couldn't be located,  did I use it incorrectly?
