### ISSUE TITLE
remote_file task helper unusable without setting shared_path

### ISSUE THREAD

**Issue by torrancew** [capistrano/capistrano#762]
It's not currently feasible to use ```remote_file``` unless ```shared_path``` is in use [(see here)](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/dsl/task_enhancements.rb#L23), however, there are some edge use cases where that may not be a requirement for a project. Can we consider making this destination path configurable, and perhaps make the default something like:```fetch(:shared_path) || ENV['TMPDIR'] || '/tmp'```, or consider removing it altogether, and assuming that it's relative? ```remote_file``` is quite a handy method to have in the DSL, and it would be awesome to have it be more flexible.

**Comment by mattbrictson** [comment]
Looks like the PRs attempted for this (#767, #783) were abandoned. I'm adding the "you can help" tag in case anyone else wants to step up and take a crack at this.

**Comment by irvingwashington** [comment]
I've briefly looked through this issue, and now I'm thinking that maybe Capistrano could simply detect if the destination path is relative (eg. `Pathname.new(t.name).relative?` ), and only then it would append it to shared_path. This would be a minimal change that would allow corner cases (when the path passed is absolute). Am I getting this right? Maybe configurable option is preferred? Either way I'd be happy to implement this.

**Comment by mattbrictson** [comment]
@leehambley Can you field this one? I have no experience with `remote_file` and it is not clear to me how it intended to be used.

**Comment by leehambley** [comment]
Given that the issue went cold for 3 years, I think it might be safe simply to close it. `remote_file` was meant to be analgous to Rake's `file` targets (As a pre-requisite driven "build" system) the `remote_file` part of Capistrano was supposed, for example to allow us to depend on a file, or directory, and have the dependency resolution meet that by cloning repos, etc, etc, to fulfil the dependency on the "release complete" file (e.g `REVISIONS` file).

It never really worked that way, and we ended up making the "body", if you will of the Cap deploy simply call methods procedurally, rather than do dependency resolution to "fulfil" a the dependency tree of a complete, successful deploy. 

I'd actually vote for marking that feature as deprecated.

**Comment by mattbrictson** [comment]
OK, I'm on board with deprecating and eventually removing the `remote_file` feature. I'll create a new issue to track that.

**Comment by mattbrictson** [comment]
Closed in favor of #1679.
