### ISSUE TITLE
Override GIT_SSH Script -- Possible?

### ISSUE THREAD

**Issue by spodlecki** [capistrano/capistrano#794]
I'm attempting to over ride GIT_SSH environment variable.

If I use

```
set :default_env, { "GIT_SSH" => "MY_BASH_SCRIPT" }
```

reports:

```
Command: ( GIT_SSH=MY_BASH_SCRIPT GIT_ASKPASS=/bin/echo GIT_SSH=/tmp/git-ssh.sh /usr/bin/env git ls-remote git@giturl )

I've also tried to break down your rake task code, and set

  set :git_environmental_variables, ->() {
    {
      git_askpass: "/bin/echo",
      git_ssh:     MY_BASH_SCRIPT"
    }
  }
```

With no result or change from the commands.

Thoughts??

Any help would be wonderful! Cap3 has been excellent, new to learn. Looking forward to this fix!

**Comment by wk8** [comment]
+1, would love to be able to do that.

**Comment by wk8** [comment]
@leehambley : mind explaining why it was important to lock it down?

**Comment by leehambley** [comment]
@wk8 the wrapper script is required because Git is badly behaved with regards to prompting for input (actually, git's networking backends, ssh and http). Regarding why the wrapper is not overridable, it is, just replace the `git:wrapper` task, it's not *trivial*, but still not too difficult. The reason it's not being worked on, we wanted to extract Git, Mercurial and Subversion to a `capistrano/scm` repository, or maybe one repository each for the SCMs. This would allow more flexibility, but alas I simply haven't had the time, and such a change will invalidate a lot of the blogs and documentation circling around, which invariably leads to an explosion of support that I often struggle to contend with.
