### ISSUE TITLE
what happened to "transaction do" of capistrano 2.x?

### ISSUE THREAD

**Issue by wiiiimm** [capistrano/capistrano#860]
trying to migrate my cap script to version 3... but cannot find anything on what to do with transaction do?

**Comment by danielbeardsley** [comment]
We must be missing something. Having a way to deal with shell commands that fail seems like an integral part of capistrano. Is it just semantics? Is there some analog to `transaction do` in Cap 3 that we just aren't aware of?

If you write *any* command-running code that uses capistrano, it seems like transactions are very useful and a no-brainer... i.e. if any given command fails, you can decide how it should be undone. I'm not entirely sure what you are suggesting here. I haven't used capistrano 3 yet, but if transaction support (do X if command Y fails) has been removed, I don't think I'll consider it.

**Comment by mattbrictson** [comment]
Sorry, as was stated above, these features are no longer present in Capistrano.

I'm assuming `transaction do...` and `on_rollback` were removed for a reason, but I can't offer any insight into that decision. What I can do for you is summarize the current behavior, which is also explained [in the official docs](http://capistranorb.com/documentation/getting-started/rollbacks/).

If a deployment fails, the `deploy:failed` task is invoked, but otherwise there is nothing automatic in terms of failure/rollback/transaction behavior.

In response to a failure, you can manually run `cap <stage> deploy:rollback`, which changes the `current` symlink to point to the previous release. It also invokes these rollback-specific tasks, allowing you to hook in additional behavior if you need it:

```
deploy:reverting
deploy:reverted
deploy:finishing_rollback
```

**Comment by danielbeardsley** [comment]
Thank you for responding. I love Capistrano and have used it for many years. I'm trying to understand what the designers of the new version intended.

> If a deployment fails

So, is it inadvisable to use capistrano for anything other than deploys? The docs certainly tout capistrano as a generic automation tool.

But this sounds like a fatal flaw for an automation tool (from [the docs](http://capistranorb.com/documentation/getting-started/rollbacks/)):
> when a task fails on one server by exiting with a non-0 exit code, Capistrano closes the SSH connections to any still in-progress servers and their tasks exit.

This seems crazy. I don't see how tasks can be designed such that they would leave their systems in a consistent state no matter which of their individual commands was aborted and killed in the middle of execution. If only there were some mechanism to run command X to clean up state when command Y fails.

I swear I must be missing something. Am I asking the wrong question? Imagine if databases had no transactional support and would leave any update query half-applied if it hit an error.

**Comment by mattbrictson** [comment]
@danielbeardsley I don't want to leave you hanging, but I can't really provide any more help here. I don't want to speculate on the design intentions, and I've already answered your questions regarding hooks for automatic rollback/cleanup behavior (there aren't any).

In my years of using Capistrano I have not encountered this use case, so I can't offer any workarounds. I write my tasks in such a way that if they were to fail, I can just run them a second time.

Perhaps you can roll your own behavior with standard Ruby exception-handling constructs, like:

```ruby
failed_hosts = []
on roles(:all) do |host|
  begin
    execute "some command that must be cleaned up if it fails"
  rescue SSHKit::Command::Failed
    failed_hosts << host
  end
end

if failed_hosts.any?
  # do something
end
```

I don't know if that even makes sense or if it would work; again, I have never come across the need for it.

If you do come across a good solution or a simple change to the code that would improve things from your perspective, we of course welcome PRs to both the code itself and to the documentation.

**Comment by leehambley** [comment]
>  I'm trying to understand what the designers of the new version intended.

The designers were myself and @seenmyfate - and the intent was to remove a misleading feature, and simplify the rather confusing error handling of the v.2 branch. 

Above all the `transaction` nomenclature was dropped as it's *precisely* not a transaction, we can't do disk/state level transactions over SSH, if you have made changes and something within the "transaction" fails, nothing magic happens to roll it back.

> But this sounds like a fatal flaw for an automation tool (from the docs):
> > when a task fails on one server by exiting with a non-0 exit code, Capistrano closes the SSH connections to any still in-progress servers and their tasks exit.

Right, we close the SSH connections (connection pooling not withstanding) and then re-open them in your recovery handlers.

The previous rollback behaviour was totally, totally inconsistent and never really worked. Some plugins (Rails) had semi-OK handling, but it was hugely, hugely dependent on which version of Rails/Bundler and the asset pipeline one had.

The new design allows you to catch errors in your own way, we have a formalized `test()` API which can be used (but, seldom is) to make assertions.

It also allows you to initiate the `deploy:rollback` (`Rake::Task['deploy:rollback'].invoke` task

It's important to note that the `deploy:rollback` calls are there as part of the documented flow for plugins to use, if you have your own recovery/rollback tasks for specific cases of tasks, you should write your own rollback handlers.

Please don't read this as aggressively as I appear to have written it, there's just a lot of detail, and people expected (and were formerly disappointed by) a lot of magic. :rocket:

**Comment by leehambley** [comment]
Also @maliqq @mattbrictson for what it's worth you don't need to use `rescue SSHKit::Command::Failed`, you can *either* use `test()` or get similar behaviour from `execute('...', raise_on_non_zero_exit: false)` which is essentially what `test()` does to wrap `execute()` anyway. (it also changes the log level, since tests tend to be noisy, and not very useful.)

**Comment by danielbeardsley** [comment]
I really appreciate the responses, Thank you!

>  as it's precisely not a transaction
That totally makes sense. `on_failure` could have been a better name.

Ok. Seems like I might be able to mimc the old behavior by wrapping the execute function.

>  I write my tasks in such a way that if they were to fail, I can just run them a second time. - @mattbrictson 
I feel like in nearly every case of server automation I can think of, leaving a machine in an inconsistent state would be a bad thing (i.e. something half-installed, some directory half-copied, some group of files half-chowned, half of a group of servers in one state and half in another), even for a little while between when it fails and when you decide it's a good idea to run it again.

Mostly, I was just surprised this isn't a more common use-case, i.e. to be able to recover from some half-applied command so that all machines are in a consistent state.

**Comment by leehambley** [comment]
> Mostly, I was just surprised this isn't a more common use-case, i.e. to be able to recover from some half-applied command so that all machines are in a consistent state.

Honestly most people choose to retry the deploy, or "rollback" by deploying an older tag/version. For much the same reason that *real* transactional systems bail out and refuse to continue if they get into a half-applied state, it's better just to try again than try and fix whatever happened.

Granted this works better when you're in a *sandbox* of a directory you don't have to symlink, and works less well for installing/changing system packages for libraries or programmes.
