### ISSUE TITLE
Do not load SCM tasks unless an SCM is defined

### ISSUE THREAD

**Issue by leehambley** [capistrano/capistrano#929]
Related to #718 and a handful of other issues which relate to deploying without an SCM, unloading the SCM, deploying via copy, tar ball, BitTorrent or quantum entanglement.

I propose, based on the work done in #718 to only load the flow, that without `set(:scm, “something”)` we should not load an SCM at all.

I propose that we could solve this by doing runtime class resolution, and autoloading of files incase a class is undefined, which may mandate changes to the structure of the SCM code. In that case we would still load the `git` namespace from `git.rake` (and others) - but avoid, if possible inserting the tools, which we could do in an `include` or similar hook in `git.rb`

**Comment by fazy** [comment]
Adding to the discussion of use cases for deployment without SCM, it's already been mentioned that a solution like Bamboo will create a package with the full, built application ready to unpack and run. For some users, this is preferable to pulling source code and building the application during the deployment process. For one thing, if you use tools like NPM (Node) or Composer (PHP), then you don't want to be dependent on so many third party resources (if I managed to get it all downloaded and working at build time, I would like to keep this for deploy).

I'm now looking at using Capistrano to deploy to a group of Amazon EC2 instances. The [cap-c2](https://github.com/forward3d/cap-ec2) project looks like it provides good support.

EC2 instances are ephemeral and elastic; new ones might be started at any time. My thinking is to have the build package available in S3, and when an instance starts for the first time it can fetch the latest build and run a local deploy script. But for already running instances, I would still like Capistrano to orchestrate this.

So I don't need scm:copy, I need either scm:none, or for the default scm:git to not get in the way.

Is this currently possible, or maybe the use case is too far removed from what Capistrano aims to do? I'm unlikely to be much help with creating a plugin as my entire Ruby knowledge is confined to what's visible in the setup guide of Capistrano. ;)

**Comment by johnkharvey** [comment]
I found a workaround-- sort of.

Here's part of my config/deploy.rb:

```
# config valid only for Capistrano 3.2.1
# Capistrano 3.3.3 includes "statistics",  which is not desirable and could not be turned off yet
lock '3.2.1'

load 'config/my_functions.rb'

set :application, 'gitignore'
set :repo_url, 'https://github.com/github/gitignore.git'

########################################################
# Unfortunately, in capistrano 3.x, you need to specify
#   an SCM target, so these variables all impact that
########################################################
set :deploy_to, '/home/someuser/git/gitignore'
set :basedir, '/home/someuser'
set :scm, :git
set :branch, 'master'
set :scm_verbose, true
# Prevent re-cloning constantly
set :deploy_via, :remote_cache
# The git repo is useless, so keep directories to 1
set :keep_releases, 1
########################################################

#==================
# Main tasks
#  - these call subtasks in config/subtasks.rb
#==================

# The "deploy" target does some funky git stuff, so we want to break him if he's run
before "deploy", :break_deploy_goal

task :clean_push do
  invoke "clean_tasks"
  invoke "do_install"
end

task :push do:
  invoke "do_install"
end

task :break_deploy_goal do
  on roles(:app), in: :parallel do |server|
    puts "---------------------------------------------"
    puts "ERROR - Do not run the 'deploy' goal directly"
    puts ""
    puts " -  Example: cap deploy_application server1"
    puts "---------------------------------------------"
    raise "Bad goal 'deploy'"
  end
end

```

Essentially, I make it so that folks can't call "deploy" directly.  If they do, it breaks.
The can call "cap <server> push" or "cap <server> clean_push", which are defined by me.
And, that tasks subtasks are defined in "config/my_functions.rb", just to keep things clean (but they are not posted here-- this is just an example).

The problem with this approach is that capistrano's entire deployment infrastructure that is completely ignored. But, on the plus side, I can essentially write ssh functions and take advantage of capistrano to organize them as such.  I figured this was a good enough tradeoff to prevent the deploy target from trying to clone things-- in this example, calling the other targets does not do any cloning; the written targets aren't a part of that lifecycle, even though the parameters are in the code.  That's why I used gitignore-- a dummy project that I wouldn't generally deploy anyway.

One note-- you'll see I froze at capistrano 3.2.1-- this is because at the time, 3.3.3 had statistics loaded which involved more external calls that I didn't want.  There may be a way to disable it now, but at the time, it was mandatory, hence I froze on 3.2.1.

I'm not sure if this helps, but this may give some folks a few ideas.

**Comment by leehambley** [comment]
Seems like you reinvented https://github.com/capistrano/sshkit/blob/master/EXAMPLES.md#using-with-rake :) If you're not using the [Capistrano flow](http://capistranorb.com/documentation/getting-started/flow/) you might as well just drop your tasks in a `Rakefile`.

I've been moving house, starting (two) new companies, and generally not active enough on my FOSS projects lately, I will eventually get around to removing the SCM from the default stuff, and just letting you plug in the flow (which is already possible, load `capistrano/flow` (`/framework`?), I think, rather than `capistrano` and it should largely just work)

**Comment by sts** [comment]
@leehambley Have you got more time yet to look into this for us? :wave:

**Comment by mattbrictson** [comment]
@leehambley @sts What if we removed explicit invocations of the SCM tasks from the deploy flow? Instead, `git.rake` etc. would hook themselves into the flow using `before` and `after`. That would allow SCM to become completely optional, perhaps at the risk at making the deploy flow a bit less obvious for the 99% case when SCM is used.

In other words:

```ruby
# deploy.rake
task :updating => :new_release_path do
  invoke "#{scm}:create_release" # REMOVE THESE
  invoke "deploy:set_current_revision"
  invoke 'deploy:symlink:shared'
end
```

And instead:

```ruby
# git.rake
after "deploy:new_release_path", "git:create_release"
before "deploy:check", "git:check"
before "deploy:set_current_revision", "git:set_current_revision"
```

This would also be a good first step to moving the SCMs into vendored or external gems.

**Comment by mattbrictson** [comment]
:arrow_up: @leehambley Would love to hear your 2¢ on my [previous comment](https://github.com/capistrano/capistrano/issues/929#issuecomment-170371959) regarding removing SCM invocations from the deploy flow and making SCMs self-contained.

If you agree this is the right direction to take, I have a working proof-of-concept for gem-ified SCMs that I'm ready to share.

**Comment by leehambley** [comment]
I think there's a bit more too the SCMs than hooking in at the right places, but it's a damned fine start. If you have a POC, let's go from there. And, thanks for being proactive.

**Comment by mattbrictson** [comment]
@leehambley Here is the POC: https://github.com/mattbrictson/experimental-capistrano-git-scm

We can move discussion to a GitHub issue in that repo if you want.

**Comment by leehambley** [comment]
Hi @mattbrictson I'm burning some midnight oil here, reviewing this whilst I wait for `dnf` to download what feels like half the world and I am *floored* by the quality of your work and clarity of thinking on the linked experimental gem. Let's do it. Should we consider *what* flavour of Git we support, or stick with what we have? I'm reminded of #1545, #1488, #1450, #1362, #1221, #1206, #1058, #985 and #886.

**Comment by leehambley** [comment]
@mattbrictson maybe it warrants discussion (on the other repo, perhaps) whether like `capistrano-rails` the git scm plugin might come with some optional extras (detect changed remotes, extra filtering of files, submodule/subtree support, etc?)

**Comment by mattbrictson** [comment]
> Should we consider what flavour of Git we support, or stick with what we have?

Just to retain my sanity, I think I'd like to implement the current flavor first, get that working with the new plugin system and released (perhaps as Capistrano 3.5) and then revisit the question of additional flavors.

There are a few different approaches we could take:

* One subclass per flavor
* One class but parameterized with constructor keyword args
* One class but parameterized with `set :git_*, …` variables

**Comment by leehambley** [comment]
I'm not sure yet, I think it depends a lot, some options are mutually exclusive (e.g the archive stragtegy can never work with submodules) but also then a strategy not using git archive strategy can't really do the attributeignore thing correctly... so it's really problematic.

**Comment by DylanFrese** [comment]
I've written an faux-SCM plugin for Capistrano that copies a set of files over to the remote (using either tar + gzip or rsync over a Net::SSH pipe). I think that having the remote server *pull* the sources from some location on the internet is the wrong way to think about deployment (in some cases it's unreasonable to have a webserver even be able to authenticate to a private repository), and having (possibly a production) server *build* a project is just unacceptable for my usecases (though I see how it wouldn't be as much of a problem for e.g. Rails). Rather, I think *pushing* a set of files to the server, and then deploying them is the more correct model.

The question is should this functionality be part of Capistrano by default? I wouldn't mind publishing my work in some form, and trying to get it better integrated into the Capistrano ecosystem.

There are a few rough edges with what I'm currently using:
  * The rsync strategy in particular is very hacky, specifically,
  * I require access to the current NetSSH connection directly, and cannot go through SSHKit
  * rsync wants to start its own ssh connection; I tell it to instead use a small script as a remote shell.
    The script runs `select(2)` in a tight loop and pipes between FDs 0, 4, 1, and 3. FDs 3 and 4
    are created by the Capistrano process, and they are then piped to and from the SSH channel.
  * There are a bundle of options (`set :copy_tar_chdir`) that modify the command line args of
     the processes, but the options understood aren't complete (don't cover the entirety of options
     available from GNU tar, for example). I'm not sure this is the right way to go about things.
  * I wrestle with the set(…) delayed execution in a couple places, in that I want to set something
    to a proc and have it *not* be evaluated when I fetch it, so I end up doing `proc {|_| ...}`.
  * I still use `set :scm, :mycustomscm`, with my copy gem invading the Capistrano namespace.
    I hear there's a new plugin infrastructure?

However, there are a couple good features I consider necessary:
  * Whitespace safe. Your files have newlines? No problem, they get deployed fine. Nothing chokes.
    You want tar to change to a directory with a space in it? Fine. The other half doesn't
    get interpreted as an argumnet
  * Transfers go from disk-to-disk. tarballs are created, compressed, sent, uncompressed, and
    extracted all in one continuous pipe.
  * Using rsync means speeding up deployments by a large factor, since rsync can intelligently
    decide not to copy files when it doesn't need to. This is especially useful if the artefacts you're
    deploying weigh around a gigabyte in size, but only 30k of files change each deploy

**Comment by mattbrictson** [comment]
@DylanFrese I think many people would appreciate a robust rsync plugin for Capistrano. This isn't my usual method of deployment, and I don't have much experience with rsync beyond the basics, so I'm afraid I can't offer much implementation advice.

> should this functionality be part of Capistrano by default?

No, we have a long-term goal of moving all SCM implementations out of Capistrano and into plugins. In terms of official documentation and sample code maintained core team, we will likely continue to recommend the pull-based-SCM strategies as the official "Capistrano way" of deploying. Of course this doesn't prevent you from publishing a plugin and adding it to the [plugins page](http://capistranorb.com/documentation/third-party-plugins/).

> There are a few rough edges

My first impression is that direct net-ssh access, using interprocess communication with rsync, etc. sounds very complicated. Keep in mind that if you choose to publish this, other people that use it will feel entitled to support. The easier you can make the solution, the easier it is to troubleshoot, and the lower the support burden will be. Good documentation also helps a lot, so also budget time for that when making your decision whether to open source.

>  I hear there's a new plugin infrastructure?

It is coming, but not released yet. You can get a sneak peak here: https://github.com/capistrano/documentation/pull/188

My final bit of advice: the pull-from-SCM approach that Capistrano uses today is particularly useful because it makes a guarantee about what will be deployed. When you `cap deploy`, you and your colleagues can be certain that a particular tag or commit was actually deployed. With a push-based approach, unless you put lots of SCM-specific safeguards in place, you could end up deploying code that hasn't been committed or pushed. Deployment is all about predictability and reproducibility, so this is something I would seriously consider before choosing a push-based solution.

**Comment by DylanFrese** [comment]
@mattbrictson 

Hey Matt.

> No, we have a long-term goal of moving all SCM implementations out of Capistrano and into plugins.

I understand this. By 'by default', I don't mean that the functionality is present in the capistrano library ('capistrano/capistrano'), just that the functionality is in some way made 'official'. If users are expected to also `gem install` a Capistrano SCM plugin when they first install Capistrano, then I suppose there would be no difference.

Using interprocess communication with `rsync` *is* complicated, but there is just no other way to tunnel rsync traffic through the tunnels Capistrano has open. The only other way is to let rsync SSH to the server itself, but I do not consider this a working implementation. If there are any differences between the SSH configuration Capistrano is using and the user's SSH configuration, as in my cases, this will flat-out not work. Even if there aren't, it's still opening another SSH connection (let alone another SSH channel) instead of reusing one from Capistrano's pool.

For reference, [here is part of the implementation](https://gist.github.com/DylanFrese/afb854245ffe7254aaf072d65dc3f3b4), the part that does all the setup work on the Ruby side.

As far as grabbing the Net::SSH connection from SSHKit, I don't really like it either. It gets into SSHKit implementation details, calls a private method (line 38 in the gist), and assumes the SSHKit backend is Net::SSH, which is not necessarily true (but is true in practice). (Line 34 also has a 'defect', in that, if the arguments passed to the server are long enough (greater than 64kb on Linux, I believe), the write to the pipe will block and the `readpartial` won't get all of the arguments.


And for philosophy on push v. pull:
Making a guarantee about what's going to be deployed, or what can be deployed is indeed valuable. But I strongly feel that these checks need to happen on the deployer's machine, not on the server being deployed to. If you have a public repository (that needs no authentication), a simple or non-existent build process, and only ever want to deploy the tip of `master` from that public repository, then the pull-based method works just fine, and gives you the guarantee that only the tip of `master` will ever be deployed without any other fuss. I'm certain I've described a lot of Rails and other Ruby projects, and that this works great for them. I don't expect Capistrano to change the way it thinks about things by default, because it grew up in the Rails etc. ecosystem.

But a 15-minute Maven build-and-test-suite that uses several gigabytes of memory and way too much CPU time cannot be run on a production server. SSH-key-forwarding to access a private repository, if not a security vulnerability, is a rather dangerous broadening of attack surface. If I do a 'push' deploy to a compromised server (that I don't know is compromised), the server gets the latest version of the built software. If I do a 'pull' deploy to a compromised server with SSH-key-forwarding, the attacker gains access to, at the very least, the private repository containing all sources. Worse, if I authenticate to my servers with the same key I use to authenticate to the git repository, the attacker now pivots to *every server in my fleet*.

Like I said, I do make the checks that changes have been committed and pushed, that origin and the current branch have not diverged or that one is behind the other. Yes, these checks are SCM-specific, but they would be anyway if it were the server doing the checking implicitly (by only fetching the tip of the default branch). They're also only 20-30 lines. If any of these checks fail, I prompt the deployer. The deployer can still choose to deploy. I think this is a feature: if absolutely necessary, a deployer can deploy hot changes immediately without having to SSH in and do a manual deploy, giving up all of the other reliability automated deployment gives. A deployer should have the have the ability to deploy what is in his/her working directory *right now* (which I also consider the far more intuitive mode of operation)¹.

A developer *shouldn't* ever have to do this, though. Normally, a developer shouldn't even be deploying, or necessarily even be allowed to deploy. **CI** should be the entity that's doing the deployment, and CI makes sure only changes that should go out to production actually do.

_1. If this, what I consider to be a feature, is undesirable, then a far simpler `git remote update && git checkout origin/master` would replicate the same qualities as a pull-based approach. Even cloning on the local machine to a temporary directory, building, and then deploying still seems far preferable to me to doing the same on the remote end._

**Comment by mattbrictson** [comment]
Thanks for taking the time to explain your use case. I understand that there are lots of scenarios like yours where deploying "from source" on the server itself is impractical, especially when expensive compilation steps are involved.

I also understand how integrating rsync is inherently complicated if you want to share Capistrano's SSH config. I'm impressed you have it working! Very cool.

If there are any changes we could make to SSHKit or Capistrano (i.e in the core) to make your job easier, please let us know by logging separate issues and we'll consider them on a case-by-case basis.

> By 'by default', I don't mean that the functionality is present in the capistrano library ('capistrano/capistrano'), just that the functionality is in some way made 'official'. If users are expected to also gem install a Capistrano SCM plugin when they first install Capistrano, then I suppose there would be no difference.

The intention is that users will be expected to add the SCM of their choice to their Gemfile and Capfile in order to enable it. So in that sense Capistrano will no longer bundle SCM plugins at all; it will be completely opt-in.

As for "official" support, that really comes down to whether we promote it in the documentation. We don't have any plans to expand the official docs beyond the Git/Hg/Svn trio that have been historically supported by the core Capistrano team members.

**Comment by DylanFrese** [comment]
The work that could be done on SSHKit's end is to abstract away the process to add a socket to Net::SSH or each backend's internal poll(2)/select(2) loop. I would expect this would be quite difficult to design from an API perspective and would cause some API bloat.

The other option is to explicitly support each backend on my side, possibly accessing normally private methods. The two backends I'm aware of SSHKit supporting are Net::SSH and local execution. Now I find it possible that, despite the work to abstract the backend away in SSHKit, there won't be any move to add more because nobody uses anything but SSH anyway. In that case, the rsync-plugin end would look like it does now, with some checks to see if SSHKit is using the local backend and then just have rsync copy locally.

**Comment by mattbrictson** [comment]
Capistrano 3.7.0.beta1 has been released! 🎉 

This version brings a new SCM plugin system, and notably for observers of this thread, it adds `set :scm, nil` to disable SCM behavior completely. You can read more about the new behavior here:

* [Custom SCM](http://capistranorb.com/documentation/advanced-features/custom-scm/) (official how-to from the docs)
* [Capistrano 3.7.0 upgrade guide](https://github.com/capistrano/capistrano/blob/master/UPGRADING-3.7.md)

After almost 3 years, I can now say that the feature is complete and I am closing this issue. Please test the beta and send us feedback!
